/**
 * Usage Instructions:
 * 
 * 1. Open your command prompt (cmd) or terminal.
 * 2. Navigate to the root directory of your project (c:\Users\Mohamed Morsi\dev\venom-new)
 * 3. Run the following command:
 * 
 *    node aggregate.js
 * 
 * This will read all the SQL migration files in the "supabase/migrations" folder,
 * sort them in numerical order, and safely concatenate them all into a single
 * "source_of_truth.sql" file.
 */

import fs from 'fs';
import path from 'path';

const dir = 'supabase/migrations';
const files = fs.readdirSync(dir).sort();

// Find all migration files starting with exactly 3 digits
const migrations = files.filter(f => /^\d{3}_.*\.sql$/.test(f));

let content = '-- CONSOLIDATED SOURCE OF TRUTH\n-- Auto-generated by aggregating all migrations sequentially\n\n';

for (const file of migrations) {
  content += '-- =====================================================================\n';
  content += '-- MIGRATION: ' + file + '\n';
  content += '-- =====================================================================\n\n';
  content += fs.readFileSync(path.join(dir, file), 'utf8') + '\n\n';
}

fs.writeFileSync(path.join(dir, 'source_of_truth.sql'), content);
console.log(`Successfully aggregated ${migrations.length} migrations into source_of_truth.sql`);
