-- CONSOLIDATED SOURCE OF TRUTH
-- Auto-generated by aggregating all migrations in order (001 to 034)

-- =====================================================================
-- MIGRATION: 001_initial_schema.sql
-- =====================================================================

-- ============================================================
-- 001_initial_schema.sql
-- Core tables for the Venom Fitness Academy gym app
-- ============================================================

-- Enable UUID generation
create extension if not exists "pgcrypto";

-- ── Profiles (linked to auth.users) ─────────────────────────

create table public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  email      text not null,
  name       text not null,
  role       text not null default 'reception'
             check (role in ('admin', 'reception', 'sales')),
  created_at timestamptz not null default now()
);

-- Auto-create profile row when a new auth user is created
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'role', 'reception')
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ── Coaches ─────────────────────────────────────────────────

create table public.coaches (
  id                 uuid primary key default gen_random_uuid(),
  name               text not null,
  payment_type       text not null default 'salary'
                     check (payment_type in ('salary', 'per_session', 'commission')),
  rate               numeric not null default 0,
  commission_base    text check (commission_base in ('revenue', 'members')),
  sessions_this_month int not null default 0,
  created_at         timestamptz not null default now()
);

-- ── Members ─────────────────────────────────────────────────

-- Sequence for human-readable display IDs (M001, M002, ...)
create sequence public.member_display_id_seq start with 1;

create table public.members (
  id                 uuid primary key default gen_random_uuid(),
  display_id         text not null unique default ('M' || lpad(nextval('member_display_id_seq')::text, 3, '0')),
  name               text not null,
  phone              text not null,
  parent_phone       text,
  birth_date         date,
  gender             text check (gender in ('male', 'female', 'other')),
  source             text not null default 'Walk-in',
  status             text not null default 'active'
                     check (status in ('active', 'expired', 'expiring_soon', 'has_debt')),
  sessions_remaining int not null default 0,
  expires_at         timestamptz not null default now(),
  member_since       timestamptz not null default now(),
  package_name       text not null default 'None',
  assigned_coach_id  uuid references public.coaches(id) on delete set null,
  freeze_days_remaining int not null default 7,
  created_at         timestamptz not null default now()
);

-- ── Subscription Packages ───────────────────────────────────

create table public.packages (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  sessions        int not null,
  price           numeric not null,
  validity_days   int not null default 30,
  freeze_days     int not null default 7,
  invitations     int not null default 0,
  inbody_sessions int not null default 0,
  created_at      timestamptz not null default now()
);

-- ── Discounts ───────────────────────────────────────────────

create table public.discounts (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  type          text not null default 'manual'
                check (type in ('seasonal', 'manual')),
  discount_type text not null default 'fixed'
                check (discount_type in ('fixed', 'percentage')),
  value         numeric not null default 0,
  active        boolean not null default true,
  created_at    timestamptz not null default now()
);

-- ── Invoices ────────────────────────────────────────────────

-- Sequence for human-readable invoice IDs
create sequence public.invoice_display_id_seq start with 1001;

create table public.invoices (
  id                   uuid primary key default gen_random_uuid(),
  display_id           text not null unique default ('INV-' || nextval('invoice_display_id_seq')::text),
  member_id            uuid not null references public.members(id) on delete cascade,
  member_name          text not null,
  package_id           uuid references public.packages(id) on delete set null,
  package_name         text not null default '',
  discount_id          uuid references public.discounts(id) on delete set null,
  discount_description text,
  discount_amount      numeric not null default 0,
  total_amount         numeric not null default 0,
  paid_amount          numeric not null default 0,
  status               text not null default 'unpaid'
                       check (status in ('paid', 'partial', 'unpaid')),
  payment_method       text not null default 'Cash'
                       check (payment_method in ('Cash', 'Visa', 'InstaPay')),
  created_at           timestamptz not null default now()
);

-- ── Discount ↔ Member (junction) ───────────────────────────

create table public.discount_members (
  discount_id uuid not null references public.discounts(id) on delete cascade,
  member_id   uuid not null references public.members(id) on delete cascade,
  primary key (discount_id, member_id)
);

-- ── Discount ↔ Invoice (junction) ──────────────────────────

create table public.discount_invoices (
  discount_id uuid not null references public.discounts(id) on delete cascade,
  invoice_id  uuid not null references public.invoices(id) on delete cascade,
  primary key (discount_id, invoice_id)
);

-- ── Leads (CRM) ────────────────────────────────────────────

create table public.leads (
  id             uuid primary key default gen_random_uuid(),
  name           text not null,
  phone          text not null,
  source         text not null default 'Walk-in',
  status         text not null default 'New'
                 check (status in ('New', 'Contacted', 'Follow-up', 'Converted', 'Lost')),
  notes          text[] not null default '{}',
  follow_up_date timestamptz not null default (now() + interval '1 day'),
  assigned_to    uuid references public.profiles(id) on delete set null,
  calls_made     int not null default 0,
  created_at     timestamptz not null default now()
);

-- ── Liabilities ─────────────────────────────────────────────

create table public.liabilities (
  id                  uuid primary key default gen_random_uuid(),
  name                text not null,
  description         text not null default '',
  type                text not null default 'installment'
                      check (type in ('installment', 'one_time')),
  total_amount        numeric not null default 0,
  paid_amount         numeric not null default 0,
  installment_amount  numeric not null default 0,
  frequency_days      int not null default 30,
  next_due_date       timestamptz not null default (now() + interval '30 days'),
  notify_days_before  int not null default 5,
  is_complete         boolean not null default false,
  created_at          timestamptz not null default now()
);

-- ── Expenses ────────────────────────────────────────────────

create table public.expenses (
  id           uuid primary key default gen_random_uuid(),
  category     text not null,
  amount       numeric not null default 0,
  description  text not null default '',
  date         timestamptz not null default now(),
  liability_id uuid references public.liabilities(id) on delete set null,
  created_at   timestamptz not null default now()
);

-- ── Audit Logs ──────────────────────────────────────────────

create table public.audit_logs (
  id             uuid primary key default gen_random_uuid(),
  action         text not null,
  action_type    text not null default 'other'
                 check (action_type in ('override_checkin', 'edit_payment', 'apply_discount', 'remove_discount', 'checkin', 'other')),
  performed_by   uuid references public.profiles(id) on delete set null,
  performer_name text not null default '',
  member_id      uuid references public.members(id) on delete set null,
  member_name    text,
  timestamp      timestamptz not null default now(),
  details        text not null default ''
);

-- ── Check-Ins (member attendance) ───────────────────────────

create table public.check_ins (
  id            uuid primary key default gen_random_uuid(),
  member_id     uuid not null references public.members(id) on delete cascade,
  checked_in_by uuid references public.profiles(id) on delete set null,
  is_override   boolean not null default false,
  pay_later     boolean not null default false,
  created_at    timestamptz not null default now()
);

-- ── Coach Check-Ins ─────────────────────────────────────────

create table public.coach_check_ins (
  id            uuid primary key default gen_random_uuid(),
  coach_id      uuid not null references public.coaches(id) on delete cascade,
  check_in_date date not null default current_date,
  created_at    timestamptz not null default now(),
  unique (coach_id, check_in_date)
);

-- ── Gym Sessions (schedule) ─────────────────────────────────

create table public.gym_sessions (
  id               uuid primary key default gen_random_uuid(),
  name             text not null,
  day_of_week      text not null,
  time             text not null,
  capacity         int not null default 20,
  coach_id         uuid references public.coaches(id) on delete set null,
  attendance_count int not null default 0,
  created_at       timestamptz not null default now()
);

-- ── Indexes ─────────────────────────────────────────────────

create index idx_members_status on public.members(status);
create index idx_members_display_id on public.members(display_id);
create index idx_invoices_member on public.invoices(member_id);
create index idx_invoices_status on public.invoices(status);
create index idx_check_ins_member on public.check_ins(member_id);
create index idx_check_ins_date on public.check_ins(created_at);
create index idx_audit_logs_type on public.audit_logs(action_type);
create index idx_audit_logs_time on public.audit_logs(timestamp);
create index idx_expenses_date on public.expenses(date);
create index idx_leads_status on public.leads(status);
create index idx_liabilities_complete on public.liabilities(is_complete);
create index idx_coach_checkins_date on public.coach_check_ins(check_in_date);


-- =====================================================================
-- MIGRATION: 002_rls_policies.sql
-- =====================================================================

-- ============================================================
-- 002_rls_policies.sql
-- (RLS REMOVED AS REQUESTED)
-- This file ensures Row Level Security is disabled and 
-- full permissions are granted to your Supabase frontend.
-- ============================================================

-- 1. Disable RLS on all tables
alter table public.profiles disable row level security;
alter table public.members disable row level security;
alter table public.packages disable row level security;
alter table public.invoices disable row level security;
alter table public.discounts disable row level security;
alter table public.discount_members disable row level security;
alter table public.discount_invoices disable row level security;
alter table public.coaches disable row level security;
alter table public.leads disable row level security;
alter table public.expenses disable row level security;
alter table public.liabilities disable row level security;
alter table public.audit_logs disable row level security;
alter table public.check_ins disable row level security;
alter table public.coach_check_ins disable row level security;
alter table public.gym_sessions disable row level security;

-- 2. Grant all privileges to the Supabase client roles
-- This ensures that your frontend application (which connects 
-- via the anon/authenticated key) has full permission to read/write.
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon;

GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;

GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;


-- =====================================================================
-- MIGRATION: 003_functions.sql
-- =====================================================================

-- ============================================================
-- 003_functions.sql
-- Database functions for transactional business logic
-- ============================================================

-- ── check_in_member ─────────────────────────────────────────
-- Decrements sessions, updates status, logs audit, creates check_in row.
-- All in a single atomic transaction.

create or replace function public.check_in_member(
  p_member_id      uuid,
  p_is_override    boolean default false,
  p_pay_later      boolean default false,
  p_performed_by   uuid default null,
  p_performer_name text default 'System'
)
returns void as $$
declare
  v_member     public.members%rowtype;
  v_new_remaining int;
  v_action     text;
  v_action_type text;
  v_details    text;
begin
  -- Lock the member row
  select * into v_member from public.members where id = p_member_id for update;

  if v_member is null then
    raise exception 'Member not found: %', p_member_id;
  end if;

  -- Decrement sessions (floor at 0, unlimited stays at 999)
  if v_member.sessions_remaining = 999 then
    v_new_remaining := 999;
  else
    v_new_remaining := greatest(0, v_member.sessions_remaining - 1);
  end if;

  -- Update member
  update public.members
  set sessions_remaining = v_new_remaining,
      status = case
        when v_new_remaining <= 2 and v_new_remaining != 999 then 'expiring_soon'
        else status
      end
  where id = p_member_id;

  -- Build audit entry
  if p_is_override then
    v_action := 'Override Check-in';
    v_action_type := 'override_checkin';
    v_details := format('Allowed %s(Pay Later) expired member %s (%s) to attend',
      case when p_pay_later then '(Pay Later) ' else '' end,
      v_member.display_id, v_member.name);
  else
    v_action := 'Check-in';
    v_action_type := 'checkin';
    v_details := format('Normal check-in: %s (%s), session deducted (%s remaining)',
      v_member.display_id, v_member.name, v_new_remaining);
  end if;

  -- Insert audit log
  insert into public.audit_logs (action, action_type, performed_by, performer_name, member_id, member_name, details)
  values (v_action, v_action_type, p_performed_by, p_performer_name, p_member_id, v_member.name, v_details);

  -- Insert check-in record
  insert into public.check_ins (member_id, checked_in_by, is_override, pay_later)
  values (p_member_id, p_performed_by, p_is_override, p_pay_later);
end;
$$ language plpgsql security definer;


-- ── pay_liability ───────────────────────────────────────────
-- Updates paid amount, marks complete if fully paid, advances due date.

create or replace function public.pay_liability(
  p_liability_id uuid,
  p_amount       numeric
)
returns void as $$
declare
  v_liability public.liabilities%rowtype;
  v_new_paid  numeric;
  v_complete  boolean;
  v_next_due  timestamptz;
begin
  select * into v_liability from public.liabilities where id = p_liability_id for update;

  if v_liability is null then
    raise exception 'Liability not found: %', p_liability_id;
  end if;

  v_new_paid := least(v_liability.paid_amount + p_amount, v_liability.total_amount);
  v_complete := v_new_paid >= v_liability.total_amount;

  -- Advance next due date for installments
  if not v_complete and v_liability.frequency_days > 0 then
    v_next_due := v_liability.next_due_date + (v_liability.frequency_days || ' days')::interval;
  else
    v_next_due := v_liability.next_due_date;
  end if;

  update public.liabilities
  set paid_amount   = v_new_paid,
      is_complete   = v_complete,
      next_due_date = v_next_due
  where id = p_liability_id;
end;
$$ language plpgsql security definer;


-- =====================================================================
-- MIGRATION: 004_seed.sql
-- =====================================================================

-- ============================================================
-- 004_seed.sql
-- Seed data matching the original mock data
-- Run AFTER creating your first admin user via Supabase Auth.
-- ============================================================

-- ── Coaches ─────────────────────────────────────────────────

insert into public.coaches (id, name, payment_type, rate, commission_base, sessions_this_month) values
  ('00000000-0000-0000-0000-000000000c01', 'Alex Turner',  'salary',     3000, null,      22),
  ('00000000-0000-0000-0000-000000000c02', 'Bella Nour',   'per_session', 80,  null,      18),
  ('00000000-0000-0000-0000-000000000c03', 'Chris Maged',  'commission',  10,  'revenue', 25);

-- ── Packages ────────────────────────────────────────────────

insert into public.packages (id, name, sessions, price, validity_days, freeze_days, invitations, inbody_sessions) values
  ('00000000-0000-0000-0000-000000000b01', '8 Sessions',        8,   350, 30, 7,  1, 1),
  ('00000000-0000-0000-0000-000000000b02', '12 Sessions',       12,  480, 30, 7,  2, 2),
  ('00000000-0000-0000-0000-000000000b03', 'Unlimited Monthly', 999, 700, 30, 14, 3, 2),
  ('00000000-0000-0000-0000-000000000b04', '16 Sessions',       16,  580, 45, 10, 2, 2);

-- ── Members ─────────────────────────────────────────────────

insert into public.members (id, display_id, name, phone, parent_phone, birth_date, gender, source, status, sessions_remaining, expires_at, member_since, package_name, assigned_coach_id, freeze_days_remaining) values
  ('00000000-0000-0000-0000-000000000a01', 'M001', 'Ahmed Al-Rashid', '055-0101', '055-0100', '1998-03-15', 'male',   'Walk-in',   'active',        8, now() + interval '14 days', now() - interval '60 days', '12 Sessions',       '00000000-0000-0000-0000-000000000c01', 7),
  ('00000000-0000-0000-0000-000000000a02', 'M002', 'Nour Hassan',     '055-0102', '055-0109', '2002-07-22', 'female', 'Instagram', 'expiring_soon', 2,  now() + interval '2 days',  now() - interval '30 days', '8 Sessions',        '00000000-0000-0000-0000-000000000c02', 4),
  ('00000000-0000-0000-0000-000000000a03', 'M003', 'Kareem Mansour',  '055-0103', null,       '1995-11-08', 'male',   'Referral',  'expired',       0, now() - interval '5 days',  now() - interval '90 days', '12 Sessions',       '00000000-0000-0000-0000-000000000c03', 7),
  ('00000000-0000-0000-0000-000000000a04', 'M004', 'Sara Al-Fahed',   '055-0104', '055-0111', '2001-01-30', 'female', 'Facebook',  'has_debt',      10, now() + interval '25 days', now() - interval '5 days',  '12 Sessions',       '00000000-0000-0000-0000-000000000c02', 7),
  ('00000000-0000-0000-0000-000000000a05', 'M005', 'Layla Ibrahim',   '055-0105', null,       '1999-05-14', 'female', 'WhatsApp',  'active',        6,  now() + interval '18 days', now() - interval '15 days', '8 Sessions',        '00000000-0000-0000-0000-000000000c02', 7),
  ('00000000-0000-0000-0000-000000000a06', 'M006', 'Omar Khalil',     '055-0106', null,       '1993-09-03', 'male',   'Walk-in',   'active',        999, now() + interval '20 days', now() - interval '10 days', 'Unlimited Monthly', '00000000-0000-0000-0000-000000000c01', 12),
  ('00000000-0000-0000-0000-000000000a07', 'M007', 'Rania Saleh',     '055-0107', '055-0120', '2003-12-19', 'female', 'Instagram', 'expiring_soon', 1, now() + interval '1 day',   now() - interval '45 days', '12 Sessions',       '00000000-0000-0000-0000-000000000c03', 7),
  ('00000000-0000-0000-0000-000000000a08', 'M008', 'Hassan Yousef',   '055-0108', null,       '1990-06-25', 'male',   'Referral',  'expired',       2, now() - interval '3 days',  now() - interval '75 days', '12 Sessions',       '00000000-0000-0000-0000-000000000c01', 7);

-- Reset the sequence to continue after our seeded data
select setval('member_display_id_seq', 8);
select setval('invoice_display_id_seq', 1006);

-- ── Discounts ───────────────────────────────────────────────

insert into public.discounts (id, name, type, discount_type, value, active) values
  ('00000000-0000-0000-0000-000000000d01', 'Ramadan Special 2025', 'seasonal',   'percentage', 15, true),
  ('00000000-0000-0000-0000-000000000d02', 'Couples Discount',     'manual',     'fixed',      50, true);

insert into public.discount_members (discount_id, member_id) values
  ('00000000-0000-0000-0000-000000000d01', '00000000-0000-0000-0000-000000000a04'),
  ('00000000-0000-0000-0000-000000000d01', '00000000-0000-0000-0000-000000000a06'),
  ('00000000-0000-0000-0000-000000000d02', '00000000-0000-0000-0000-000000000a01'),
  ('00000000-0000-0000-0000-000000000d02', '00000000-0000-0000-0000-000000000a05');

-- ── Invoices ────────────────────────────────────────────────

insert into public.invoices (id, display_id, member_id, member_name, package_id, package_name, discount_id, discount_description, discount_amount, total_amount, paid_amount, status, payment_method, created_at) values
  ('00000000-0000-0000-0000-000000000e01', 'INV-1001', '00000000-0000-0000-0000-000000000a01', 'Ahmed Al-Rashid', '00000000-0000-0000-0000-000000000b02', '12 Sessions',       null,                                     null,                 0,  480, 480, 'paid',    'Visa',     now() - interval '15 days'),
  ('00000000-0000-0000-0000-000000000e02', 'INV-1002', '00000000-0000-0000-0000-000000000a04', 'Sara Al-Fahed',   '00000000-0000-0000-0000-000000000b02', '12 Sessions',       '00000000-0000-0000-0000-000000000d01',   'Ramadan promotion',  50, 480, 200, 'partial', 'Cash',     now() - interval '5 days'),
  ('00000000-0000-0000-0000-000000000e03', 'INV-1003', '00000000-0000-0000-0000-000000000a05', 'Layla Ibrahim',   '00000000-0000-0000-0000-000000000b01', '8 Sessions',        null,                                     null,                 0,  350, 350, 'paid',    'InstaPay', now() - interval '15 days'),
  ('00000000-0000-0000-0000-000000000e04', 'INV-1004', '00000000-0000-0000-0000-000000000a06', 'Omar Khalil',     '00000000-0000-0000-0000-000000000b03', 'Unlimited Monthly', '00000000-0000-0000-0000-000000000d01',   'Ramadan promotion',  70, 700, 0,   'unpaid',  'Cash',     now() - interval '10 days'),
  ('00000000-0000-0000-0000-000000000e05', 'INV-1005', '00000000-0000-0000-0000-000000000a07', 'Rania Saleh',     '00000000-0000-0000-0000-000000000b02', '12 Sessions',       null,                                     null,                 0,  480, 480, 'paid',    'Visa',     now() - interval '45 days'),
  ('00000000-0000-0000-0000-000000000e06', 'INV-1006', '00000000-0000-0000-0000-000000000a02', 'Nour Hassan',     '00000000-0000-0000-0000-000000000b01', '8 Sessions',        null,                                     null,                 0,  350, 350, 'paid',    'Cash',     now());

insert into public.discount_invoices (discount_id, invoice_id) values
  ('00000000-0000-0000-0000-000000000d01', '00000000-0000-0000-0000-000000000e02'),
  ('00000000-0000-0000-0000-000000000d01', '00000000-0000-0000-0000-000000000e04');

-- ── Leads ───────────────────────────────────────────────────

insert into public.leads (name, phone, source, status, notes, follow_up_date, calls_made) values
  ('David Miller',   '055-0201', 'Instagram', 'New',       '{}',                                                             now() + interval '1 day',  0),
  ('Emma Al-Sayed',  '055-0202', 'Walk-in',   'Contacted', '{"Interested in unlimited package","Wants trial session"}',       now() + interval '2 days', 2),
  ('Firas Nabil',    '055-0203', 'Facebook',  'Follow-up', '{"Budget concern","Offered discount"}',                           now(),                     3),
  ('Ghada Farouk',   '055-0204', 'Referral',  'Converted', '{"Converted to 12 sessions package"}',                            now() - interval '1 day',  1),
  ('Hana Ziad',      '055-0205', 'WhatsApp',  'Lost',      '{"Went with competitor"}',                                        now() - interval '5 days', 4);

-- ── Expenses ────────────────────────────────────────────────

insert into public.expenses (category, amount, description, date) values
  ('Salaries',         12000, 'Monthly coach salaries',      now() - interval '5 days'),
  ('Maintenance',       450,  'Treadmill belt replacement',  now() - interval '3 days'),
  ('Government Bills', 1200,  'Electricity bill',            now() - interval '8 days'),
  ('Purchases',         800,  'Resistance bands restock',    now());

-- ── Liabilities ─────────────────────────────────────────────

insert into public.liabilities (name, description, type, total_amount, paid_amount, installment_amount, frequency_days, next_due_date, notify_days_before, is_complete) values
  ('Commercial Treadmill Set', '8 commercial treadmills purchased for cardio zone', 'installment', 24000, 6000, 2000, 30, now() + interval '3 days',  5, false),
  ('AC System Upgrade',        'Full HVAC upgrade for main gym floor',              'one_time',    8500,  0,    8500, 0,  now() + interval '12 days', 5, false),
  ('Reception Renovation',     'New reception desk, chairs, and lighting',          'installment', 15000, 7500, 2500, 30, now() + interval '18 days', 5, false);

-- ── Gym Sessions ────────────────────────────────────────────

insert into public.gym_sessions (name, day_of_week, time, capacity, coach_id, attendance_count) values
  ('Morning HIIT',      'Sunday',    '07:00', 20, '00000000-0000-0000-0000-000000000c01', 18),
  ('Yoga Flow',         'Sunday',    '09:00', 15, '00000000-0000-0000-0000-000000000c02', 12),
  ('Strength Training', 'Monday',    '07:00', 20, '00000000-0000-0000-0000-000000000c03', 15),
  ('Spin Class',        'Monday',    '18:00', 20, '00000000-0000-0000-0000-000000000c01', 20),
  ('Boxing',            'Tuesday',   '07:00', 12, '00000000-0000-0000-0000-000000000c03', 10),
  ('Pilates',           'Wednesday', '09:00', 12, '00000000-0000-0000-0000-000000000c02', 8),
  ('CrossFit',          'Thursday',  '07:00', 20, '00000000-0000-0000-0000-000000000c01', 16),
  ('Evening HIIT',      'Thursday',  '19:00', 20, '00000000-0000-0000-0000-000000000c03', 19),
  ('Morning HIIT',      'Saturday',  '08:00', 20, '00000000-0000-0000-0000-000000000c01', 14),
  ('Open Gym',          'Friday',    '10:00', 30, '00000000-0000-0000-0000-000000000c02', 22);

-- ── Audit Logs (sample) ─────────────────────────────────────

insert into public.audit_logs (action, action_type, performer_name, member_id, member_name, timestamp, details) values
  ('Override Check-in', 'override_checkin', 'Admin',     '00000000-0000-0000-0000-000000000a03', 'Kareem Mansour',  now(),                      'Allowed expired member M003 (Kareem Mansour) to attend'),
  ('Edit Payment',      'edit_payment',     'Reception', null,                                    null,              now() - interval '1 hour',  'Updated INV-1002: partial payment recorded, amount 200 EGP'),
  ('Apply Discount',    'apply_discount',   'Admin',     null,                                    null,              now() - interval '1 day',   'Applied Ramadan Special 2025 (15%) to INV-1004'),
  ('Check-in',          'checkin',          'Reception', '00000000-0000-0000-0000-000000000a01', 'Ahmed Al-Rashid', now() - interval '30 min',  'Normal check-in: M001 (Ahmed Al-Rashid), session deducted (8 remaining)'),
  ('Check-in',          'checkin',          'Reception', '00000000-0000-0000-0000-000000000a05', 'Layla Ibrahim',   now() - interval '90 min',  'Normal check-in: M005 (Layla Ibrahim), session deducted (6 remaining)');


-- =====================================================================
-- MIGRATION: 005_member_number.sql
-- =====================================================================

-- ============================================================
-- 005_rename_id.sql
-- Rename id to uuid, add numeric id
-- ============================================================

ALTER TABLE public.members RENAME COLUMN id TO uuid;
ALTER TABLE public.members ADD COLUMN id int;

-- Backfill existing members with sequential numbers based on display_id
-- Parse the numeric part of display_id (e.g., 'M001' → 1)
UPDATE public.members
SET id = CAST(REPLACE(display_id, 'M', '') AS int)
WHERE display_id LIKE 'M%' AND id IS NULL;

ALTER TABLE public.members DROP COLUMN display_id;

-- Create a sequence for future member numbers
CREATE SEQUENCE IF NOT EXISTS public.member_id_seq;
SELECT setval('member_id_seq', COALESCE((SELECT MAX(id) FROM public.members WHERE id > 0), 0));

-- Create index for id lookups
CREATE INDEX IF NOT EXISTS idx_members_id ON public.members(id);


-- =====================================================================
-- MIGRATION: 006_member_sport_class.sql
-- =====================================================================

-- ============================================================
-- 006_member_sport_class.sql
-- Add sport field to members
-- ============================================================

ALTER TABLE public.members
  ADD COLUMN IF NOT EXISTS sport text;


-- =====================================================================
-- MIGRATION: 007_invoice_id.sql
-- =====================================================================

-- ============================================================
-- 007_invoice_id.sql
-- Rename invoice columns, add member subscription tracking,
-- create trigger to auto-update member on invoice creation
-- ============================================================

-- ── 1. Invoice column renames ───────────────────────────────
ALTER TABLE public.invoices RENAME COLUMN id TO uuid;
ALTER TABLE public.invoices RENAME COLUMN display_id TO id;

-- ── 2. Add subscription tracking columns to members ─────────
ALTER TABLE public.members
  ADD COLUMN IF NOT EXISTS package_id uuid REFERENCES public.packages(id) ON DELETE SET NULL;

ALTER TABLE public.members
  ADD COLUMN IF NOT EXISTS invitations_remaining int NOT NULL DEFAULT 0;

ALTER TABLE public.members
  ADD COLUMN IF NOT EXISTS inbody_sessions_remaining int NOT NULL DEFAULT 0;

-- ── 3. Trigger: auto-update member subscription on invoice insert ──

CREATE OR REPLACE FUNCTION public.handle_invoice_created()
RETURNS trigger AS $$
DECLARE
  v_pkg public.packages%rowtype;
BEGIN
  -- Only update member if the invoice references a package
  IF NEW.package_id IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT * INTO v_pkg FROM public.packages WHERE id = NEW.package_id;

  IF v_pkg IS NULL THEN
    RETURN NEW;
  END IF;

  UPDATE public.members
  SET
    package_id                = v_pkg.id,
    package_name              = v_pkg.name,
    sessions_remaining        = v_pkg.sessions,
    freeze_days_remaining     = v_pkg.freeze_days,
    invitations_remaining     = v_pkg.invitations,
    inbody_sessions_remaining = v_pkg.inbody_sessions,
    expires_at                = now() + (v_pkg.validity_days || ' days')::interval,
    status                    = 'active'
  WHERE uuid = NEW.member_id;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_invoice_created
  AFTER INSERT ON public.invoices
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_invoice_created();

-- ── 4. Fix check_in_member function (display_id was removed in 005) ──

CREATE OR REPLACE FUNCTION public.check_in_member(
  p_member_id      uuid,
  p_is_override    boolean DEFAULT false,
  p_pay_later      boolean DEFAULT false,
  p_performed_by   uuid DEFAULT null,
  p_performer_name text DEFAULT 'System'
)
RETURNS void AS $$
DECLARE
  v_member     public.members%rowtype;
  v_new_remaining int;
  v_action     text;
  v_action_type text;
  v_details    text;
BEGIN
  -- Lock the member row
  SELECT * INTO v_member FROM public.members WHERE uuid = p_member_id FOR UPDATE;

  IF v_member IS NULL THEN
    RAISE EXCEPTION 'Member not found: %', p_member_id;
  END IF;

  -- Decrement sessions (floor at 0, unlimited stays at 999)
  IF v_member.sessions_remaining = 999 THEN
    v_new_remaining := 999;
  ELSE
    v_new_remaining := greatest(0, v_member.sessions_remaining - 1);
  END IF;

  -- Update member
  UPDATE public.members
  SET sessions_remaining = v_new_remaining,
      status = CASE
        WHEN v_new_remaining <= 2 AND v_new_remaining != 999 THEN 'expiring_soon'
        ELSE status
      END
  WHERE uuid = p_member_id;

  -- Build audit entry
  IF p_is_override THEN
    v_action := 'Override Check-in';
    v_action_type := 'override_checkin';
    v_details := format('Allowed %sexpired member #%s (%s) to attend',
      CASE WHEN p_pay_later THEN '(Pay Later) ' ELSE '' END,
      v_member.id, v_member.name);
  ELSE
    v_action := 'Check-in';
    v_action_type := 'checkin';
    v_details := format('Normal check-in: #%s (%s), session deducted (%s remaining)',
      v_member.id, v_member.name, v_new_remaining);
  END IF;

  -- Insert audit log
  INSERT INTO public.audit_logs (action, action_type, performed_by, performer_name, member_id, member_name, details)
  VALUES (v_action, v_action_type, p_performed_by, p_performer_name, p_member_id, v_member.name, v_details);

  -- Insert check-in record
  INSERT INTO public.check_ins (member_id, checked_in_by, is_override, pay_later)
  VALUES (p_member_id, p_performed_by, p_is_override, p_pay_later);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ── 5. Cleanup function for expired subscriptions ─────────────

CREATE OR REPLACE FUNCTION public.cleanup_expired_subscriptions()
RETURNS void AS $$
BEGIN
  UPDATE public.members
  SET
    package_id = null,
    package_name = 'None',
    sessions_remaining = 0,
    freeze_days_remaining = 0,
    invitations_remaining = 0,
    inbody_sessions_remaining = 0,
    status = 'expired'
  WHERE expires_at < now() AND status != 'expired';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================================
-- MIGRATION: 008_new_member_status.sql
-- =====================================================================

-- Drop constraint and recreate with 'new' status
ALTER TABLE public.members DROP CONSTRAINT IF EXISTS members_status_check;
ALTER TABLE public.members ADD CONSTRAINT members_status_check CHECK (status in ('active', 'expired', 'expiring_soon', 'has_debt', 'new'));

-- Make expires_at nullable
ALTER TABLE public.members ALTER COLUMN expires_at DROP NOT NULL;
ALTER TABLE public.members ALTER COLUMN expires_at DROP DEFAULT;


-- =====================================================================
-- MIGRATION: 009_coach_phone.sql
-- =====================================================================

ALTER TABLE public.coaches ADD COLUMN IF NOT EXISTS phone text NOT NULL DEFAULT '';


-- =====================================================================
-- MIGRATION: 010_coach_sport.sql
-- =====================================================================

ALTER TABLE public.coaches ADD COLUMN IF NOT EXISTS sport text;


-- =====================================================================
-- MIGRATION: 011_classes_refactor.sql
-- =====================================================================

-- ============================================================
-- 011_classes_refactor.sql
-- Refactor sports, gym_sessions -> classes, update members/coaches
-- ============================================================

-- 1. Create sports table
CREATE TABLE IF NOT EXISTS public.sports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 2. Create classes table
CREATE TABLE IF NOT EXISTS public.classes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  sport_id uuid REFERENCES public.sports(id) ON DELETE CASCADE,
  coach_id uuid REFERENCES public.coaches(id) ON DELETE SET NULL,
  schedules jsonb NOT NULL DEFAULT '[]'::jsonb,
  capacity int NOT NULL DEFAULT 20,
  attendance_count int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 3. Modify members table
ALTER TABLE public.members DROP COLUMN IF EXISTS sport;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS class_id uuid REFERENCES public.classes(id) ON DELETE SET NULL;

-- 4. Modify coaches table
ALTER TABLE public.coaches DROP COLUMN IF EXISTS sport;

-- 5. Drop old gym_sessions
DROP TABLE IF EXISTS public.gym_sessions;

-- 6. Grants
GRANT ALL ON TABLE public.sports TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.classes TO anon, authenticated, service_role;


-- =====================================================================
-- MIGRATION: 012_remove_assigned_coach.sql
-- =====================================================================

-- ============================================================
-- 012_remove_assigned_coach.sql
-- Remove assigned_coach_id from members and update check_in_member RPC
-- ============================================================

-- 1. Remove assigned_coach_id from members
ALTER TABLE public.members DROP COLUMN IF EXISTS assigned_coach_id;

-- 2. Update check_in_member RPC to use class coach
CREATE OR REPLACE FUNCTION public.check_in_member(
  p_member_id      uuid,
  p_is_override    boolean DEFAULT false,
  p_pay_later      boolean DEFAULT false,
  p_performed_by   uuid DEFAULT null,
  p_performer_name text DEFAULT 'System'
)
RETURNS void AS $$
DECLARE
  v_member     public.members%rowtype;
  v_class_coach uuid;
  v_new_remaining int;
  v_action     text;
  v_action_type text;
  v_details    text;
BEGIN
  -- Lock the member row
  SELECT * INTO v_member FROM public.members WHERE id = p_member_id FOR UPDATE;

  IF v_member IS NULL THEN
    RAISE EXCEPTION 'Member not found: %', p_member_id;
  END IF;

  -- Decrement sessions (floor at 0, unlimited stays at 999)
  IF v_member.sessions_remaining = 999 THEN
    v_new_remaining := 999;
  ELSE
    v_new_remaining := GREATEST(0, v_member.sessions_remaining - 1);
  END IF;

  -- Determine action type and details
  IF p_is_override THEN
    v_action_type := 'override_checkin';
    v_details := 'Manual override check-in (expired/empty)';
  ELSE
    v_action_type := 'checkin';
    IF p_pay_later THEN
      v_details := 'Checked in - session deducted (Pay Later)';
    ELSE
      v_details := 'Checked in - session deducted';
    END IF;
  END IF;

  -- Update member
  UPDATE public.members
  SET sessions_remaining = v_new_remaining
  WHERE id = p_member_id;

  -- Increment coach session count if applicable (based on assigned class)
  IF v_member.class_id IS NOT NULL THEN
    SELECT coach_id INTO v_class_coach FROM public.classes WHERE id = v_member.class_id;
    IF v_class_coach IS NOT NULL THEN
      UPDATE public.coaches
      SET sessions_this_month = sessions_this_month + 1
      WHERE id = v_class_coach;
    END IF;
  END IF;

  -- Log to audit_logs
  INSERT INTO public.audit_logs (
    action_type, 
    member_name, 
    performed_by_name, 
    details
  ) VALUES (
    v_action_type,
    v_member.name,
    p_performer_name,
    v_details
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================================
-- MIGRATION: 013_fix_checkin_rpc.sql
-- =====================================================================

-- ============================================================
-- 013_fix_checkin_rpc.sql
-- Fix UUID lookup in check_in_member and enforce sessions limit
-- ============================================================

CREATE OR REPLACE FUNCTION public.check_in_member(
  p_member_id      uuid,
  p_is_override    boolean DEFAULT false,
  p_pay_later      boolean DEFAULT false,
  p_performed_by   uuid DEFAULT null,
  p_performer_name text DEFAULT 'System'
)
RETURNS void AS $$
DECLARE
  v_member     public.members%rowtype;
  v_class_coach uuid;
  v_new_remaining int;
  v_action     text;
  v_action_type text;
  v_details    text;
BEGIN
  -- Lock the member row
  SELECT * INTO v_member FROM public.members WHERE uuid = p_member_id FOR UPDATE;

  IF v_member IS NULL THEN
    RAISE EXCEPTION 'Member not found: %', p_member_id;
  END IF;

  -- Validation: Ensure sessions are available for non-override check-ins
  IF NOT p_is_override AND v_member.sessions_remaining <= 0 THEN
    RAISE EXCEPTION 'Member has no sessions remaining.';
  END IF;

  -- Decrement sessions (floor at 0, unlimited stays at 999)
  IF v_member.sessions_remaining = 999 THEN
    v_new_remaining := 999;
  ELSE
    v_new_remaining := GREATEST(0, v_member.sessions_remaining - 1);
  END IF;

  -- Update member
  UPDATE public.members
  SET sessions_remaining = v_new_remaining,
      status = CASE
        WHEN v_new_remaining <= 2 AND v_new_remaining != 999 THEN 'expiring_soon'
        ELSE status
      END
  WHERE uuid = p_member_id;

  -- Increment coach session count if applicable (based on assigned class)
  IF v_member.class_id IS NOT NULL THEN
    SELECT coach_id INTO v_class_coach FROM public.classes WHERE id = v_member.class_id;
    IF v_class_coach IS NOT NULL THEN
      UPDATE public.coaches
      SET sessions_this_month = sessions_this_month + 1
      WHERE id = v_class_coach;
    END IF;
  END IF;

  -- Build audit entry
  IF p_is_override THEN
    v_action := 'Override Check-in';
    v_action_type := 'override_checkin';
    v_details := format('Allowed %s(Pay Later) expired member %s (%s) to attend',
      CASE WHEN p_pay_later THEN '(Pay Later) ' ELSE '' END,
      v_member.id, v_member.name);
  ELSE
    v_action := 'Check-in';
    v_action_type := 'checkin';
    v_details := format('Normal check-in: %s (%s), session deducted (%s remaining)',
      v_member.id, v_member.name, v_new_remaining);
  END IF;

  -- Insert audit log
  INSERT INTO public.audit_logs (action, action_type, performed_by, performer_name, member_id, member_name, details)
  VALUES (v_action, v_action_type, p_performed_by, p_performer_name, p_member_id, v_member.name, v_details);

  -- Insert check-in record
  INSERT INTO public.check_ins (member_id, checked_in_by, is_override, pay_later)
  VALUES (p_member_id, p_performed_by, p_is_override, p_pay_later);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================================
-- MIGRATION: 014_remove_member_source.sql
-- =====================================================================

-- ============================================================
-- 014_remove_member_source.sql
-- Remove source column from members table
-- ============================================================

ALTER TABLE public.members DROP COLUMN IF EXISTS source;


-- =====================================================================
-- MIGRATION: 015_remove_totals.sql
-- =====================================================================

-- migration 015_remove_totals.sql

-- Add the new freeze_days_remaining column
ALTER TABLE public.members ADD COLUMN freeze_days_remaining int not null default 7;

-- Backfill data: remaining = max(0, total - used)
UPDATE public.members 
SET freeze_days_remaining = GREATEST(0, freeze_days_total - freeze_days_used);

-- Drop the old columns
ALTER TABLE public.members DROP COLUMN freeze_days_used;
ALTER TABLE public.members DROP COLUMN freeze_days_total;
ALTER TABLE public.members DROP COLUMN total_sessions;


-- =====================================================================
-- MIGRATION: 016_fix_checkin_rpc.sql
-- =====================================================================

-- migration 016_fix_checkin_rpc.sql

CREATE OR REPLACE FUNCTION public.check_in_member(
  p_member_id      uuid,
  p_is_override    boolean DEFAULT false,
  p_pay_later      boolean DEFAULT false,
  p_performed_by   uuid DEFAULT null,
  p_performer_name text DEFAULT 'System'
)
RETURNS void AS $$
DECLARE
  v_member     public.members%rowtype;
  v_class_coach uuid;
  v_new_remaining int;
  v_action     text;
  v_action_type text;
  v_details    text;
BEGIN
  -- Lock the member row
  SELECT * INTO v_member FROM public.members WHERE uuid = p_member_id FOR UPDATE;

  IF v_member IS NULL THEN
    RAISE EXCEPTION 'Member not found: %', p_member_id;
  END IF;

  -- Validation: Ensure sessions are available for non-override check-ins
  IF NOT p_is_override AND v_member.sessions_remaining <= 0 THEN
    RAISE EXCEPTION 'Member has no sessions remaining.';
  END IF;

  -- Decrement sessions (floor at 0, unlimited stays at 999)
  IF v_member.sessions_remaining = 999 THEN
    v_new_remaining := 999;
  ELSE
    v_new_remaining := GREATEST(0, v_member.sessions_remaining - 1);
  END IF;

  -- Update member
  UPDATE public.members
  SET sessions_remaining = v_new_remaining,
      status = CASE
        WHEN v_new_remaining <= 2 AND v_new_remaining != 999 THEN 'expiring_soon'
        ELSE status
      END
  WHERE uuid = p_member_id;

  -- Increment coach session count if applicable (based on assigned class)
  IF v_member.class_id IS NOT NULL THEN
    SELECT coach_id INTO v_class_coach FROM public.classes WHERE id = v_member.class_id;
    IF v_class_coach IS NOT NULL THEN
      UPDATE public.coaches
      SET sessions_this_month = sessions_this_month + 1
      WHERE id = v_class_coach;
    END IF;
  END IF;

  -- Build audit entry
  IF p_is_override THEN
    v_action := 'Override Check-in';
    v_action_type := 'override_checkin';
    v_details := format('Allowed %s(Pay Later) expired member %s (%s) to attend',
      CASE WHEN p_pay_later THEN '(Pay Later) ' ELSE '' END,
      v_member.id, v_member.name);
  ELSE
    v_action := 'Check-in';
    v_action_type := 'checkin';
    v_details := format('Normal check-in: %s (%s), session deducted (%s remaining)',
      v_member.id, v_member.name, v_new_remaining);
  END IF;

  -- Insert audit log
  INSERT INTO public.audit_logs (action, action_type, performed_by, performer_name, member_id, member_name, details)
  VALUES (v_action, v_action_type, p_performed_by, p_performer_name, p_member_id, v_member.name, v_details);

  -- Insert check-in record
  INSERT INTO public.check_ins (member_id, checked_in_by, is_override, pay_later)
  VALUES (p_member_id, p_performed_by, p_is_override, p_pay_later);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================================
-- MIGRATION: 017_fix_invoice_trigger.sql
-- =====================================================================

-- migration 017_fix_invoice_trigger.sql

CREATE OR REPLACE FUNCTION public.handle_invoice_created()
RETURNS trigger AS $$
DECLARE
  v_pkg public.packages%rowtype;
BEGIN
  -- Only update member if the invoice references a package
  IF NEW.package_id IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT * INTO v_pkg FROM public.packages WHERE id = NEW.package_id;

  IF v_pkg IS NULL THEN
    RETURN NEW;
  END IF;

  UPDATE public.members
  SET
    package_id                = v_pkg.id,
    package_name              = v_pkg.name,
    sessions_remaining        = v_pkg.sessions,
    freeze_days_remaining     = v_pkg.freeze_days,
    invitations_remaining     = v_pkg.invitations,
    inbody_sessions_remaining = v_pkg.inbody_sessions,
    expires_at                = NEW.created_at + (v_pkg.validity_days || ' days')::interval,
    status                    = 'active'
  WHERE uuid = NEW.member_id;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================================
-- MIGRATION: 018_strict_freeze.sql
-- =====================================================================

-- migration 018_strict_freeze.sql

ALTER TABLE public.members ADD COLUMN IF NOT EXISTS frozen_until timestamptz;

CREATE OR REPLACE FUNCTION public.check_in_member(
  p_member_id      uuid,
  p_is_override    boolean DEFAULT false,
  p_pay_later      boolean DEFAULT false,
  p_performed_by   uuid DEFAULT null,
  p_performer_name text DEFAULT 'System'
)
RETURNS void AS $$
DECLARE
  v_member     public.members%rowtype;
  v_class_coach uuid;
  v_new_remaining int;
  v_action     text;
  v_action_type text;
  v_details    text;
  v_unused_freeze_days int;
BEGIN
  -- Lock the member row
  SELECT * INTO v_member FROM public.members WHERE uuid = p_member_id FOR UPDATE;

  IF v_member IS NULL THEN
    RAISE EXCEPTION 'Member not found: %', p_member_id;
  END IF;

  -- Check freeze status
  IF v_member.frozen_until IS NOT NULL AND v_member.frozen_until > now() THEN
    IF NOT p_is_override THEN
      RAISE EXCEPTION 'Member is frozen until %. Please cancel freeze to check-in.', to_char(v_member.frozen_until, 'YYYY-MM-DD');
    ELSE
      -- Calculate unused freeze days (ceiling of diff in days)
      v_unused_freeze_days := CEIL(EXTRACT(EPOCH FROM (v_member.frozen_until - now())) / 86400);
      IF v_unused_freeze_days > 0 THEN
        -- Subtract from expires_at, do NOT refund freeze_days_remaining
        UPDATE public.members
        SET 
          expires_at = expires_at - (v_unused_freeze_days || ' days')::interval,
          frozen_until = null
        WHERE uuid = p_member_id;
      ELSE
        UPDATE public.members SET frozen_until = null WHERE uuid = p_member_id;
      END IF;
    END IF;
  ELSE
    -- Just clear it if it's passed
    IF v_member.frozen_until IS NOT NULL THEN
      UPDATE public.members SET frozen_until = null WHERE uuid = p_member_id;
    END IF;
  END IF;

  -- Validation: Ensure sessions are available for non-override check-ins
  IF NOT p_is_override AND v_member.sessions_remaining <= 0 THEN
    RAISE EXCEPTION 'Member has no sessions remaining.';
  END IF;

  -- Decrement sessions (floor at 0, unlimited stays at 999)
  IF v_member.sessions_remaining = 999 THEN
    v_new_remaining := 999;
  ELSE
    v_new_remaining := GREATEST(0, v_member.sessions_remaining - 1);
  END IF;

  -- Update member
  UPDATE public.members
  SET sessions_remaining = v_new_remaining,
      status = CASE
        WHEN v_new_remaining <= 2 AND v_new_remaining != 999 THEN 'expiring_soon'
        ELSE status
      END
  WHERE uuid = p_member_id;

  -- Increment coach session count if applicable (based on assigned class)
  IF v_member.class_id IS NOT NULL THEN
    SELECT coach_id INTO v_class_coach FROM public.classes WHERE id = v_member.class_id;
    IF v_class_coach IS NOT NULL THEN
      UPDATE public.coaches
      SET sessions_this_month = sessions_this_month + 1
      WHERE id = v_class_coach;
    END IF;
  END IF;

  -- Build audit entry
  IF p_is_override THEN
    v_action := 'Override Check-in';
    v_action_type := 'override_checkin';
    v_details := format('Allowed %s(Pay Later) expired or frozen member %s (%s) to attend',
      CASE WHEN p_pay_later THEN '(Pay Later) ' ELSE '' END,
      v_member.id, v_member.name);
  ELSE
    v_action := 'Check-in';
    v_action_type := 'checkin';
    v_details := format('Normal check-in: %s (%s), session deducted (%s remaining)',
      v_member.id, v_member.name, v_new_remaining);
  END IF;

  -- Insert audit log
  INSERT INTO public.audit_logs (action, action_type, performed_by, performer_name, member_id, member_name, details)
  VALUES (v_action, v_action_type, p_performed_by, p_performer_name, p_member_id, v_member.name, v_details);

  -- Insert check-in record
  INSERT INTO public.check_ins (member_id, checked_in_by, is_override, pay_later)
  VALUES (p_member_id, p_performed_by, p_is_override, p_pay_later);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================================
-- MIGRATION: 019_custom_roles.sql
-- =====================================================================

-- ============================================================
-- 019_custom_roles.sql
-- Create roles and user_roles tables to support dynamic RBAC
-- ============================================================

-- 1. Create `roles` table
CREATE TABLE IF NOT EXISTS public.roles (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  description text,
  tabs text[] not null default '{}',
  created_at timestamptz not null default now()
);

-- 2. Create `user_roles` linking table
CREATE TABLE IF NOT EXISTS public.user_roles (
  user_id uuid not null references public.profiles(id) on delete cascade,
  role_id uuid not null references public.roles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

-- 3. Insert default roles
INSERT INTO public.roles (name, description, tabs) VALUES
  ('admin', 'Admin - full access', ARRAY['/', '/checkin', '/members', '/subscriptions', '/invoices', '/discounts', '/finance', '/daily', '/reports', '/coaches', '/classes', '/sports', '/leads', '/liabilities', '/audit', '/users']),
  ('reception', 'Reception - operational tabs', ARRAY['/', '/checkin', '/members', '/invoices', '/finance', '/coaches', '/classes', '/sports', '/daily', '/liabilities']),
  ('sales', 'Sales - members & leads only', ARRAY['/', '/members', '/leads'])
ON CONFLICT (name) DO UPDATE SET tabs = EXCLUDED.tabs, description = EXCLUDED.description;

-- 4. Migrate existing profiles data into user_roles
DO $$
DECLARE
  r_admin uuid;
  r_reception uuid;
  r_sales uuid;
BEGIN
  SELECT id INTO r_admin FROM public.roles WHERE name = 'admin';
  SELECT id INTO r_reception FROM public.roles WHERE name = 'reception';
  SELECT id INTO r_sales FROM public.roles WHERE name = 'sales';

  -- Insert mappings
  INSERT INTO public.user_roles (user_id, role_id)
  SELECT p.id, r_admin
  FROM public.profiles p
  WHERE p.role = 'admin'
  ON CONFLICT DO NOTHING;

  INSERT INTO public.user_roles (user_id, role_id)
  SELECT p.id, r_reception
  FROM public.profiles p
  WHERE p.role = 'reception'
  ON CONFLICT DO NOTHING;

  INSERT INTO public.user_roles (user_id, role_id)
  SELECT p.id, r_sales
  FROM public.profiles p
  WHERE p.role = 'sales'
  ON CONFLICT DO NOTHING;
END $$;

-- 5. Drop the old check constraint on profiles.role (if it exists)
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;

-- 6. Update handle_new_user trigger to use user_roles
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  v_role_id uuid;
  v_role_name text;
BEGIN
  -- Determine initial role name (default 'reception')
  v_role_name := coalesce(new.raw_user_meta_data->>'role', 'reception');
  
  -- Insert into profiles (keep the legacy role field for now, just in case)
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    v_role_name
  );
  
  -- Find the corresponding role ID
  SELECT id INTO v_role_id FROM public.roles WHERE name = v_role_name LIMIT 1;
  
  IF v_role_id IS NOT NULL THEN
    -- Insert into user_roles
    insert into public.user_roles (user_id, role_id)
    values (new.id, v_role_id);
  END IF;

  return new;
end;
$$ language plpgsql security definer;

-- Set up RLS for roles and user_roles
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated read access to roles"
ON public.roles FOR SELECT
TO authenticated USING (true);

CREATE POLICY "Allow authenticated read access to user_roles"
ON public.user_roles FOR SELECT
TO authenticated USING (true);


-- =====================================================================
-- MIGRATION: 020_fix_custom_roles_permissions.sql
-- =====================================================================

-- ============================================================
-- 020_fix_custom_roles_permissions.sql
-- Fix 403 Forbidden errors by disabling RLS and granting permissions
-- to match the rest of the application.
-- ============================================================

-- Disable RLS to match the rest of the schema
ALTER TABLE public.roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles DISABLE ROW LEVEL SECURITY;

-- Drop the restrictive policies added in 019
DROP POLICY IF EXISTS "Allow authenticated read access to roles" ON public.roles;
DROP POLICY IF EXISTS "Allow authenticated read access to user_roles" ON public.user_roles;

-- Grant all privileges to the Supabase client roles (anon & authenticated)
GRANT ALL ON TABLE public.roles TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.user_roles TO anon, authenticated, service_role;


-- =====================================================================
-- MIGRATION: 021_drop_legacy_role_column.sql
-- =====================================================================

-- ============================================================
-- 021_drop_legacy_role_column.sql
-- Drop the legacy 'role' column from profiles now that
-- the user_roles table is fully implemented.
-- ============================================================

-- 1. Drop the column
ALTER TABLE public.profiles DROP COLUMN IF EXISTS role;

-- 2. Update the trigger to remove the reference to the role column
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  v_role_id uuid;
  v_role_name text;
BEGIN
  -- Determine initial role name (default 'reception')
  v_role_name := coalesce(new.raw_user_meta_data->>'role', 'reception');
  
  -- Insert into profiles without the role column
  insert into public.profiles (id, email, name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1))
  );
  
  -- Find the corresponding role ID
  SELECT id INTO v_role_id FROM public.roles WHERE name = v_role_name LIMIT 1;
  
  IF v_role_id IS NOT NULL THEN
    -- Insert into user_roles
    insert into public.user_roles (user_id, role_id)
    values (new.id, v_role_id);
  END IF;

  return new;
end;
$$ language plpgsql security definer;


-- =====================================================================
-- MIGRATION: 022_update_class_attendance_trigger.sql
-- =====================================================================

-- ============================================================
-- 022_update_class_attendance_trigger.sql
-- Automatically manage class attendance_count based on members.class_id
-- ============================================================

-- First, correct any existing attendance counts
UPDATE public.classes c
SET attendance_count = (
  SELECT count(*) FROM public.members m WHERE m.class_id = c.id
);

-- Function to handle attendance count changes
CREATE OR REPLACE FUNCTION public.handle_member_class_change()
RETURNS trigger AS $$
BEGIN
  -- If updating and the class_id didn't change, do nothing
  IF TG_OP = 'UPDATE' AND OLD.class_id IS NOT DISTINCT FROM NEW.class_id THEN
    RETURN NEW;
  END IF;

  -- Decrement old class
  IF (TG_OP = 'UPDATE' OR TG_OP = 'DELETE') AND OLD.class_id IS NOT NULL THEN
    UPDATE public.classes 
    SET attendance_count = attendance_count - 1 
    WHERE id = OLD.class_id;
  END IF;
  
  -- Increment new class
  IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') AND NEW.class_id IS NOT NULL THEN
    UPDATE public.classes 
    SET attendance_count = attendance_count + 1 
    WHERE id = NEW.class_id;
  END IF;
  
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop existing trigger if it exists
DROP TRIGGER IF EXISTS trigger_member_class_change ON public.members;

-- Create the trigger
CREATE TRIGGER trigger_member_class_change
AFTER INSERT OR UPDATE OF class_id OR DELETE ON public.members
FOR EACH ROW EXECUTE FUNCTION public.handle_member_class_change();


-- =====================================================================
-- MIGRATION: 023_cleanup_coach_commission.sql
-- =====================================================================

1.

-- =====================================================================
-- MIGRATION: 024_coach_checkins_refactor.sql
-- =====================================================================

-- ============================================================
-- 024_coach_checkins_refactor.sql
-- Overhaul coach check-ins to support specific classes and 
-- remove the static sessions_this_month tracker.
-- ============================================================

-- 1. Add class_id to coach_check_ins
ALTER TABLE public.coach_check_ins 
ADD COLUMN class_id uuid REFERENCES public.classes(id) ON DELETE CASCADE;

-- 2. Drop the old unique constraint (1 check-in per day)
ALTER TABLE public.coach_check_ins 
DROP CONSTRAINT IF EXISTS coach_check_ins_coach_id_check_in_date_key;

-- 3. Add the new unique constraint (1 check-in per class per day)
-- We use NULLS NOT DISTINCT if possible, but standard UNIQUE is fine for now
ALTER TABLE public.coach_check_ins 
ADD CONSTRAINT coach_check_ins_coach_id_date_class_key UNIQUE (coach_id, check_in_date, class_id);

-- 4. Drop the obsolete sessions_this_month column from coaches
ALTER TABLE public.coaches 
DROP COLUMN IF EXISTS sessions_this_month;


-- =====================================================================
-- MIGRATION: 025_allow_multiple_coach_checkins.sql
-- =====================================================================

��- -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
 - -   0 2 5 _ a l l o w _ m u l t i p l e _ c o a c h _ c h e c k i n s . s q l 
 - -   A l l o w   c o a c h e s   t o   c h e c k   i n   m u l t i p l e   t i m e s   t o   t h e   s a m e   c l a s s   
 - -   o n   t h e   s a m e   d a y   i f   t h e y   h a v e   m u l t i p l e   s l o t s . 
 - -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
 
 A L T E R   T A B L E   p u b l i c . c o a c h _ c h e c k _ i n s   
 D R O P   C O N S T R A I N T   I F   E X I S T S   c o a c h _ c h e c k _ i n s _ c o a c h _ i d _ d a t e _ c l a s s _ k e y ;  
 

-- =====================================================================
-- MIGRATION: 026_clinic_packages.sql
-- =====================================================================

��- -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
 - -   0 2 6 _ c l i n i c _ p a c k a g e s . s q l 
 - -   A d d   i s _ c l i n i c   f l a g   t o   p a c k a g e s 
 - -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
 
 A L T E R   T A B L E   p u b l i c . p a c k a g e s   A D D   C O L U M N   i s _ c l i n i c   B O O L E A N   N O T   N U L L   D E F A U L T   f a l s e ;  
 

-- =====================================================================
-- MIGRATION: 027_lead_invitations.sql
-- =====================================================================

��- -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
 - -   0 2 7 _ l e a d _ i n v i t a t i o n s . s q l 
 - -   A d d   i n v i t i n g _ m e m b e r _ i d   t o   l e a d s 
 - -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
 
 A L T E R   T A B L E   p u b l i c . l e a d s   A D D   C O L U M N   i n v i t i n g _ m e m b e r _ i d   U U I D   R E F E R E N C E S   p u b l i c . m e m b e r s ( u u i d ) ;  
 

-- =====================================================================
-- MIGRATION: 028_invoice_activation.sql
-- =====================================================================

-- ============================================================
-- 028_invoice_activation.sql
-- Add activation_date and is_applied to invoices
-- ============================================================

-- ── 1. Add columns ───────────────────────────────
ALTER TABLE public.invoices
ADD COLUMN IF NOT EXISTS activation_date timestamp with time zone,
ADD COLUMN IF NOT EXISTS is_applied boolean NOT NULL DEFAULT false;

-- Backfill existing invoices
UPDATE public.invoices
SET activation_date = created_at, is_applied = true
WHERE activation_date IS NULL;

-- ── 2. Update trigger ───────────────────────────────
DROP TRIGGER IF EXISTS on_invoice_created ON public.invoices;

CREATE OR REPLACE FUNCTION public.handle_invoice_created()
RETURNS trigger AS $$
DECLARE
  v_pkg public.packages%rowtype;
BEGIN
  IF NEW.package_id IS NULL THEN
    NEW.is_applied := true;
    RETURN NEW;
  END IF;

  -- Default activation_date to created_at if not provided
  IF NEW.activation_date IS NULL THEN
    NEW.activation_date := NEW.created_at;
  END IF;

  SELECT * INTO v_pkg FROM public.packages WHERE id = NEW.package_id;
  IF v_pkg IS NULL THEN
    NEW.is_applied := true;
    RETURN NEW;
  END IF;

  -- If activation_date is in the future, don't apply yet
  IF NEW.activation_date > now() THEN
    NEW.is_applied := false;
    RETURN NEW;
  END IF;

  -- Otherwise, apply now
  UPDATE public.members
  SET
    package_id                = v_pkg.id,
    package_name              = v_pkg.name,
    sessions_remaining        = v_pkg.sessions,
    freeze_days_remaining     = v_pkg.freeze_days,
    invitations_remaining     = v_pkg.invitations,
    inbody_sessions_remaining = v_pkg.inbody_sessions,
    expires_at                = NEW.activation_date + (v_pkg.validity_days || ' days')::interval,
    status                    = 'active'
  WHERE uuid = NEW.member_id;

  NEW.is_applied := true;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_invoice_created_before
  BEFORE INSERT ON public.invoices
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_invoice_created();

-- ── 3. Create activation RPC ───────────────────────────────
CREATE OR REPLACE FUNCTION public.activate_pending_subscriptions()
RETURNS void AS $$
DECLARE
  v_inv public.invoices%rowtype;
  v_pkg public.packages%rowtype;
BEGIN
  FOR v_inv IN 
    SELECT * FROM public.invoices 
    WHERE is_applied = false 
      AND activation_date <= now()
      AND package_id IS NOT NULL
    ORDER BY activation_date ASC
  LOOP
    SELECT * INTO v_pkg FROM public.packages WHERE id = v_inv.package_id;
    IF v_pkg IS NOT NULL THEN
      UPDATE public.members
      SET
        package_id                = v_pkg.id,
        package_name              = v_pkg.name,
        sessions_remaining        = v_pkg.sessions,
        freeze_days_remaining     = v_pkg.freeze_days,
        invitations_remaining     = v_pkg.invitations,
        inbody_sessions_remaining = v_pkg.inbody_sessions,
        expires_at                = v_inv.activation_date + (v_pkg.validity_days || ' days')::interval,
        status                    = 'active'
      WHERE uuid = v_inv.member_id;
    END IF;
    
    UPDATE public.invoices
    SET is_applied = true
    WHERE uuid = v_inv.uuid;
  END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================================
-- MIGRATION: 029_discount_groups.sql
-- =====================================================================

��A L T E R   T A B L E   d i s c o u n t s   A D D   C O L U M N   i s _ j o i n t   B O O L E A N   D E F A U L T   f a l s e ,   A D D   C O L U M N   j o i n t _ c o u n t   I N T E G E R   D E F A U L T   1 ;   D R O P   T A B L E   I F   E X I S T S   d i s c o u n t _ m e m b e r s ;  
 

-- =====================================================================
-- MIGRATION: 030_remove_discount_type.sql
-- =====================================================================

��A L T E R   T A B L E   d i s c o u n t s   D R O P   C O L U M N   I F   E X I S T S   t y p e ;  
 

-- =====================================================================
-- MIGRATION: 031_drop_discount_invoices.sql
-- =====================================================================

��D R O P   T A B L E   I F   E X I S T S   d i s c o u n t _ i n v o i c e s ;  
 

-- =====================================================================
-- MIGRATION: 032_negative_sessions.sql
-- =====================================================================

-- 032_negative_sessions.sql

-- Add session_debt column
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS session_debt int NOT NULL DEFAULT 0;

-- 1. check_in_member updates
CREATE OR REPLACE FUNCTION public.check_in_member(
  p_member_id      uuid,
  p_is_override    boolean DEFAULT false,
  p_pay_later      boolean DEFAULT false,
  p_performed_by   uuid DEFAULT null,
  p_performer_name text DEFAULT 'System'
)
RETURNS void AS $$
DECLARE
  v_member     public.members%rowtype;
  v_class_coach uuid;
  v_new_remaining int;
  v_action     text;
  v_action_type text;
  v_details    text;
  v_unused_freeze_days int;
  v_is_clinic  boolean;
BEGIN
  -- Lock the member row
  SELECT * INTO v_member FROM public.members WHERE uuid = p_member_id FOR UPDATE;

  IF v_member IS NULL THEN
    RAISE EXCEPTION 'Member not found: %', p_member_id;
  END IF;

  -- Check freeze status
  IF v_member.frozen_until IS NOT NULL AND v_member.frozen_until > now() THEN
    IF NOT p_is_override THEN
      RAISE EXCEPTION 'Member is frozen until %. Please cancel freeze to check-in.', to_char(v_member.frozen_until, 'YYYY-MM-DD');
    ELSE
      -- Calculate unused freeze days (ceiling of diff in days)
      v_unused_freeze_days := CEIL(EXTRACT(EPOCH FROM (v_member.frozen_until - now())) / 86400);
      IF v_unused_freeze_days > 0 THEN
        -- Subtract from expires_at, do NOT refund freeze_days_remaining
        UPDATE public.members
        SET 
          expires_at = expires_at - (v_unused_freeze_days || ' days')::interval,
          frozen_until = null
        WHERE uuid = p_member_id;
      ELSE
        UPDATE public.members SET frozen_until = null WHERE uuid = p_member_id;
      END IF;
    END IF;
  ELSE
    -- Just clear it if it's passed
    IF v_member.frozen_until IS NOT NULL THEN
      UPDATE public.members SET frozen_until = null WHERE uuid = p_member_id;
    END IF;
  END IF;

  -- Check if current package is clinic
  v_is_clinic := false;
  IF v_member.id = -1 THEN
    v_is_clinic := true;
  ELSIF v_member.package_id IS NOT NULL THEN
    SELECT is_clinic INTO v_is_clinic FROM public.packages WHERE id = v_member.package_id;
  END IF;

  IF p_is_override THEN
    IF v_is_clinic THEN
      RAISE EXCEPTION 'Cannot override check-in for clinic packages.';
    END IF;
    IF v_member.sessions_remaining <= -3 THEN
      RAISE EXCEPTION 'Member has reached the maximum allowed override debt of -3 sessions.';
    END IF;
  ELSE
    -- Normal check-in
    IF v_member.sessions_remaining <= 0 THEN
      RAISE EXCEPTION 'Member has no sessions remaining.';
    END IF;
  END IF;

  -- Decrement sessions (floor at 0 normally, -3 for override, unlimited stays at 999)
  IF v_member.sessions_remaining = 999 THEN
    v_new_remaining := 999;
  ELSIF p_is_override THEN
    v_new_remaining := GREATEST(-3, v_member.sessions_remaining - 1);
  ELSE
    v_new_remaining := GREATEST(0, v_member.sessions_remaining - 1);
  END IF;

  -- Update member
  UPDATE public.members
  SET sessions_remaining = v_new_remaining,
      status = CASE
        WHEN v_new_remaining <= 2 AND v_new_remaining != 999 AND v_new_remaining > 0 THEN 'expiring_soon'
        ELSE status
      END
  WHERE uuid = p_member_id;

  -- Increment coach session count if applicable (based on assigned class)
  IF v_member.class_id IS NOT NULL THEN
    SELECT coach_id INTO v_class_coach FROM public.classes WHERE id = v_member.class_id;
    IF v_class_coach IS NOT NULL THEN
      UPDATE public.coaches
      SET sessions_this_month = sessions_this_month + 1
      WHERE id = v_class_coach;
    END IF;
  END IF;

  -- Build audit entry
  IF p_is_override THEN
    v_action := 'Override Check-in';
    v_action_type := 'override_checkin';
    v_details := format('Allowed %s(Pay Later) expired or frozen member %s (%s) to attend. Session debt: %s',
      CASE WHEN p_pay_later THEN '(Pay Later) ' ELSE '' END,
      v_member.id, v_member.name, v_new_remaining);
  ELSE
    v_action := 'Check-in';
    v_action_type := 'checkin';
    v_details := format('Normal check-in: %s (%s), session deducted (%s remaining)',
      v_member.id, v_member.name, v_new_remaining);
  END IF;

  -- Insert audit log
  INSERT INTO public.audit_logs (action, action_type, performed_by, performer_name, member_id, member_name, details)
  VALUES (v_action, v_action_type, p_performed_by, p_performer_name, p_member_id, v_member.name, v_details);

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 2. handle_invoice_created update
CREATE OR REPLACE FUNCTION public.handle_invoice_created()
RETURNS trigger AS $$
DECLARE
  v_pkg public.packages%rowtype;
  v_member public.members%rowtype;
  v_new_sessions int;
  v_new_debt int;
BEGIN
  IF NEW.package_id IS NULL THEN
    NEW.is_applied := true;
    RETURN NEW;
  END IF;

  -- Default activation_date to created_at if not provided
  IF NEW.activation_date IS NULL THEN
    NEW.activation_date := NEW.created_at;
  END IF;

  SELECT * INTO v_pkg FROM public.packages WHERE id = NEW.package_id;
  IF v_pkg IS NULL THEN
    NEW.is_applied := true;
    RETURN NEW;
  END IF;

  -- If activation_date is in the future, don't apply yet
  IF NEW.activation_date > now() THEN
    NEW.is_applied := false;
    RETURN NEW;
  END IF;

  -- Fetch the member to check for session debt
  SELECT * INTO v_member FROM public.members WHERE uuid = NEW.member_id;
  IF v_member IS NULL THEN
    NEW.is_applied := true;
    RETURN NEW;
  END IF;

  -- Calculate new sessions with debt
  IF v_pkg.is_clinic THEN
    v_new_sessions := v_pkg.sessions;
    v_new_debt := v_member.session_debt;
    IF v_member.sessions_remaining < 0 THEN
      v_new_debt := v_new_debt + ABS(v_member.sessions_remaining);
    END IF;
  ELSE
    v_new_debt := v_member.session_debt;
    IF v_member.sessions_remaining < 0 THEN
      v_new_debt := v_new_debt + ABS(v_member.sessions_remaining);
    END IF;
    
    v_new_sessions := v_pkg.sessions - v_new_debt;
    v_new_debt := 0;
  END IF;

  -- Otherwise, apply now
  UPDATE public.members
  SET
    package_id                = v_pkg.id,
    package_name              = v_pkg.name,
    sessions_remaining        = v_new_sessions,
    session_debt              = v_new_debt,
    freeze_days_remaining     = v_pkg.freeze_days,
    invitations_remaining     = v_pkg.invitations,
    inbody_sessions_remaining = v_pkg.inbody_sessions,
    expires_at                = NEW.activation_date + (v_pkg.validity_days || ' days')::interval,
    status                    = 'active'
  WHERE uuid = NEW.member_id;

  NEW.is_applied := true;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 3. activate_pending_subscriptions update
CREATE OR REPLACE FUNCTION public.activate_pending_subscriptions()
RETURNS void AS $$
DECLARE
  v_inv public.invoices%rowtype;
  v_pkg public.packages%rowtype;
  v_member public.members%rowtype;
  v_new_sessions int;
  v_new_debt int;
BEGIN
  FOR v_inv IN 
    SELECT * FROM public.invoices 
    WHERE is_applied = false 
      AND activation_date <= now()
      AND package_id IS NOT NULL
    ORDER BY activation_date ASC
  LOOP
    SELECT * INTO v_pkg FROM public.packages WHERE id = v_inv.package_id;
    IF v_pkg IS NOT NULL THEN
      
      SELECT * INTO v_member FROM public.members WHERE uuid = v_inv.member_id;
      
      IF v_member IS NOT NULL THEN
        IF v_pkg.is_clinic THEN
          v_new_sessions := v_pkg.sessions;
          v_new_debt := v_member.session_debt;
          IF v_member.sessions_remaining < 0 THEN
            v_new_debt := v_new_debt + ABS(v_member.sessions_remaining);
          END IF;
        ELSE
          v_new_debt := v_member.session_debt;
          IF v_member.sessions_remaining < 0 THEN
            v_new_debt := v_new_debt + ABS(v_member.sessions_remaining);
          END IF;
          
          v_new_sessions := v_pkg.sessions - v_new_debt;
          v_new_debt := 0;
        END IF;

        UPDATE public.members
        SET
          package_id                = v_pkg.id,
          package_name              = v_pkg.name,
          sessions_remaining        = v_new_sessions,
          session_debt              = v_new_debt,
          freeze_days_remaining     = v_pkg.freeze_days,
          invitations_remaining     = v_pkg.invitations,
          inbody_sessions_remaining = v_pkg.inbody_sessions,
          expires_at                = v_inv.activation_date + (v_pkg.validity_days || ' days')::interval,
          status                    = 'active'
        WHERE uuid = v_inv.member_id;
      END IF;
    END IF;
    
    UPDATE public.invoices
    SET is_applied = true
    WHERE uuid = v_inv.uuid;
  END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================================
-- MIGRATION: 033_auto_admin.sql
-- =====================================================================

-- ============================================================
-- 033_auto_admin.sql
-- Automatically make the first registered user an Admin
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  v_role_id uuid;
  v_role_name text;
  v_user_count int;
BEGIN
  -- Check if this is the very first user in the database
  SELECT count(*) INTO v_user_count FROM public.profiles;

  IF v_user_count = 0 THEN
    v_role_name := 'admin';
  ELSE
    -- Determine initial role name (default 'reception')
    v_role_name := coalesce(new.raw_user_meta_data->>'role', 'reception');
  END IF;
  
  -- Insert into profiles (keep the legacy role field for now)
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    v_role_name
  );
  
  -- Find the corresponding role ID
  SELECT id INTO v_role_id FROM public.roles WHERE name = v_role_name LIMIT 1;
  
  IF v_role_id IS NOT NULL THEN
    -- Insert into user_roles
    insert into public.user_roles (user_id, role_id)
    values (new.id, v_role_id);
  END IF;

  return new;
end;
$$ language plpgsql security definer;


-- =====================================================================
-- MIGRATION: 034_numeric_invoice_ids.sql
-- =====================================================================

-- Remove the old sequence default
ALTER TABLE public.invoices ALTER COLUMN id DROP DEFAULT;

-- Function to set invoice ID to the max number + 1 if not provided
CREATE OR REPLACE FUNCTION public.set_invoice_id()
RETURNS trigger AS $$
DECLARE
  v_max_id int;
BEGIN
  IF NEW.id IS NULL OR NEW.id = '' THEN
    SELECT max(NULLIF(regexp_replace(id, '\D', '', 'g'), '')::int) INTO v_max_id FROM public.invoices;
    IF v_max_id IS NULL THEN
      v_max_id := 1000;
    END IF;
    NEW.id := (v_max_id + 1)::text;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_invoice_id ON public.invoices;
CREATE TRIGGER trg_set_invoice_id
  BEFORE INSERT ON public.invoices
  FOR EACH ROW
  EXECUTE FUNCTION public.set_invoice_id();

-- Update existing records to remove the 'INV-' prefix
UPDATE public.invoices SET id = replace(id, 'INV-', '') WHERE id LIKE 'INV-%';


