-- CONSOLIDATED SOURCE OF TRUTH
-- Auto-generated by aggregating all migrations in order (001 to 034)

-- =====================================================================
-- MIGRATION: 001_initial_schema.sql
-- =====================================================================

-- ============================================================
-- 001_initial_schema.sql
-- Core tables for the Venom Fitness Academy gym app
-- ============================================================

-- Enable UUID generation
create extension if not exists "pgcrypto";

-- ── Profiles (linked to auth.users) ─────────────────────────

create table public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  email      text not null,
  name       text not null,
  role       text not null default 'reception'
             check (role in ('admin', 'reception', 'sales')),
  created_at timestamptz not null default now()
);

-- Auto-create profile row when a new auth user is created
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'role', 'reception')
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ── Coaches ─────────────────────────────────────────────────
-- CONSOLIDATED SOURCE OF TRUTH
-- Auto-generated by aggregating all migrations in order (001 to 034)

-- =====================================================================
-- MIGRATION: 001_initial_schema.sql
-- =====================================================================

-- ============================================================
-- 001_initial_schema.sql
-- Core tables for the Venom Fitness Academy gym app
-- ============================================================

-- Enable UUID generation
create extension if not exists "pgcrypto";

-- ── Profiles (linked to auth.users) ─────────────────────────

create table public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  email      text not null,
  name       text not null,
  role       text not null default 'reception'
             check (role in ('admin', 'reception', 'sales')),
  created_at timestamptz not null default now()
);

-- Auto-create profile row when a new auth user is created
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'role', 'reception')
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ── Coaches ─────────────────────────────────────────────────

create table public.coaches (
  id                 uuid primary key default gen_random_uuid(),
  name               text not null,
  payment_type       text not null default 'salary'
                     check (payment_type in ('salary', 'per_session')),
  rate               numeric not null default 0,
  created_at         timestamptz not null default now()
);

-- ── Members ─────────────────────────────────────────────────

-- Sequence for human-readable display IDs (M001, M002, ...)
create sequence public.member_display_id_seq start with 1;

create table public.members (
  id                 uuid primary key default gen_random_uuid(),
  display_id         text not null unique default ('M' || lpad(nextval('member_display_id_seq')::text, 3, '0')),
  name               text not null,
  phone              text not null,
  parent_phone       text,
  birth_date         date,
  gender             text check (gender in ('male', 'female')),
  source             text not null default 'Walk-in',
  status             text not null default 'active'
                     check (status in ('active', 'expired', 'expiring_soon', 'has_debt')),
  sessions_remaining int not null default 0,
  expires_at         timestamptz not null default now(),
  member_since       timestamptz not null default now(),
  package_name       text not null default 'None',
  assigned_coach_id  uuid references public.coaches(id) on delete set null,
  freeze_days_remaining int not null default 7,
  created_at         timestamptz not null default now()
);

-- ── Subscription Packages ───────────────────────────────────

create table public.packages (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  sessions        int not null,
  price           numeric not null,
  validity_days   int not null default 30,
  freeze_days     int not null default 7,
  invitations     int not null default 0,
  inbody_sessions int not null default 0,
  created_at      timestamptz not null default now()
);

-- ── Discounts ───────────────────────────────────────────────

create table public.discounts (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  type          text not null default 'manual'
                check (type in ('seasonal', 'manual')),
  discount_type text not null default 'fixed'
                check (discount_type in ('fixed', 'percentage')),
  value         numeric not null default 0,
  active        boolean not null default true,
  created_at    timestamptz not null default now()
);

-- ── Invoices ────────────────────────────────────────────────

-- Sequence for human-readable invoice IDs
create sequence public.invoice_display_id_seq start with 1001;

create table public.invoices (
  id                   uuid primary key default gen_random_uuid(),
  display_id           text not null unique default ('INV-' || nextval('invoice_display_id_seq')::text),
  member_id            uuid not null references public.members(id) on delete cascade,
  member_name          text not null,
  package_id           uuid references public.packages(id) on delete set null,
  package_name         text not null default '',
  discount_id          uuid references public.discounts(id) on delete set null,
  discount_description text,
  discount_amount      numeric not null default 0,
  total_amount         numeric not null default 0,
  paid_amount          numeric not null default 0,
  status               text not null default 'unpaid'
                       check (status in ('paid', 'partial', 'unpaid')),
  payment_method       text not null default 'Cash'
                       check (payment_method in ('Cash', 'Visa', 'InstaPay', 'Split')),
  split_payments       jsonb,
  created_at           timestamptz not null default now()
);

-- ── Discount ↔ Member (junction) ───────────────────────────

create table public.discount_members (
  discount_id uuid not null references public.discounts(id) on delete cascade,
  member_id   uuid not null references public.members(id) on delete cascade,
  primary key (discount_id, member_id)
);

-- ── Discount ↔ Invoice (junction) ──────────────────────────

create table public.discount_invoices (
  discount_id uuid not null references public.discounts(id) on delete cascade,
  invoice_id  uuid not null references public.invoices(id) on delete cascade,
  primary key (discount_id, invoice_id)
);

-- ── Leads (CRM) ────────────────────────────────────────────

create table public.leads (
  id             uuid primary key default gen_random_uuid(),
  name           text not null,
  phone          text not null,
  source         text not null default 'Walk-in',
  status         text not null default 'New'
                 check (status in ('New', 'Contacted', 'Follow-up', 'Converted', 'Lost')),
  notes          text[] not null default '{}',
  interest       text,
  inviting_member_id uuid references public.members(id) on delete set null,
  follow_up_date timestamptz not null default (now() + interval '1 day'),
  assigned_to    uuid references public.profiles(id) on delete set null,
  calls_made     int not null default 0,
  created_at     timestamptz not null default now()
);

-- ── Liabilities ─────────────────────────────────────────────

create table public.liabilities (
  id                  uuid primary key default gen_random_uuid(),
  name                text not null,
  description         text not null default '',
  type                text not null default 'installment'
                      check (type in ('installment', 'one_time')),
  total_amount        numeric not null default 0,
  paid_amount         numeric not null default 0,
  installment_amount  numeric not null default 0,
  frequency_days      int not null default 30,
  next_due_date       timestamptz not null default (now() + interval '30 days'),
  notify_days_before  int not null default 5,
  is_complete         boolean not null default false,
  created_at          timestamptz not null default now()
);

-- ── Expenses ────────────────────────────────────────────────

create table public.expenses (
  uuid         uuid primary key default gen_random_uuid(),
GRANT ALL ON TABLE public.sports TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.classes TO anon, authenticated, service_role;


-- =====================================================================
-- MIGRATION: 012_remove_assigned_coach.sql
-- =====================================================================

-- ============================================================
-- 012_remove_assigned_coach.sql
-- Remove assigned_coach_id from members and update check_in_member RPC
-- ============================================================

-- 1. Remove assigned_coach_id from members
ALTER TABLE public.members DROP COLUMN IF EXISTS assigned_coach_id;

-- 2. Update check_in_member RPC to use class coach
CREATE OR REPLACE FUNCTION public.check_in_member(
  p_member_id      uuid,
  p_is_override    boolean DEFAULT false,
  p_pay_later      boolean DEFAULT false,
  p_performed_by   uuid DEFAULT null,
  p_performer_name text DEFAULT 'System'
)
RETURNS void AS $$
DECLARE
  v_member     public.members%rowtype;
  v_class_coach uuid;
  v_new_remaining int;
  v_action     text;
  v_action_type text;
  v_details    text;
BEGIN
  -- Lock the member row
  SELECT * INTO v_member FROM public.members WHERE id = p_member_id FOR UPDATE;

  IF v_member IS NULL THEN
    RAISE EXCEPTION 'Member not found: %', p_member_id;
  END IF;

  -- Decrement sessions (floor at 0, unlimited stays at 999)
  IF v_member.sessions_remaining = 999 THEN
    v_new_remaining := 999;
  ELSE
    v_new_remaining := GREATEST(0, v_member.sessions_remaining - 1);
  END IF;

  -- Determine action type and details
  IF p_is_override THEN
    v_action_type := 'override_checkin';
    v_details := 'Manual override check-in (expired/empty)';
  ELSE
    v_action_type := 'checkin';
    IF p_pay_later THEN
      v_details := 'Checked in - session deducted (Pay Later)';
    ELSE
      v_details := 'Checked in - session deducted';
    END IF;
  END IF;

  -- Update member
  UPDATE public.members
  SET sessions_remaining = v_new_remaining
  WHERE id = p_member_id;

  -- Increment coach session count if applicable (based on assigned class)
  IF v_member.class_id IS NOT NULL THEN
    SELECT coach_id INTO v_class_coach FROM public.classes WHERE id = v_member.class_id;
    IF v_class_coach IS NOT NULL THEN
      UPDATE public.coaches
      SET sessions_this_month = sessions_this_month + 1
      WHERE id = v_class_coach;
    END IF;
  END IF;

  -- Log to audit_logs
  INSERT INTO public.audit_logs (
    action_type, 
    member_name, 
    performed_by_name, 
    details
  ) VALUES (
    v_action_type,
    v_member.name,
    p_performer_name,
    v_details
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================================
-- MIGRATION: 013_fix_checkin_rpc.sql
-- =====================================================================

-- ============================================================
-- 013_fix_checkin_rpc.sql
-- Fix UUID lookup in check_in_member and enforce sessions limit
-- ============================================================

CREATE OR REPLACE FUNCTION public.check_in_member(
  p_member_id      uuid,
  p_is_override    boolean DEFAULT false,
  p_pay_later      boolean DEFAULT false,
  p_performed_by   uuid DEFAULT null,
  p_performer_name text DEFAULT 'System'
)
RETURNS void AS $$
DECLARE
  v_member     public.members%rowtype;
  v_class_coach uuid;
  v_new_remaining int;
  v_action     text;
  v_action_type text;
  v_details    text;
BEGIN
  -- Lock the member row
  SELECT * INTO v_member FROM public.members WHERE uuid = p_member_id FOR UPDATE;

  IF v_member IS NULL THEN
    RAISE EXCEPTION 'Member not found: %', p_member_id;
  END IF;

  -- Validation: Ensure sessions are available for non-override check-ins
  IF NOT p_is_override AND v_member.sessions_remaining <= 0 THEN
    RAISE EXCEPTION 'Member has no sessions remaining.';
  END IF;

  -- Decrement sessions (floor at 0, unlimited stays at 999)
  IF v_member.sessions_remaining = 999 THEN
    v_new_remaining := 999;
  ELSE
    v_new_remaining := GREATEST(0, v_member.sessions_remaining - 1);
  END IF;

  -- Update member
  UPDATE public.members
  SET sessions_remaining = v_new_remaining,
      status = CASE
        WHEN v_new_remaining <= 2 AND v_new_remaining != 999 THEN 'expiring_soon'
        ELSE status
      END
  WHERE uuid = p_member_id;

  -- Increment coach session count if applicable (based on assigned class)
  IF v_member.class_id IS NOT NULL THEN
    SELECT coach_id INTO v_class_coach FROM public.classes WHERE id = v_member.class_id;
    IF v_class_coach IS NOT NULL THEN
      UPDATE public.coaches
      SET sessions_this_month = sessions_this_month + 1
      WHERE id = v_class_coach;
    END IF;
  END IF;

  -- Build audit entry
  IF p_is_override THEN
    v_action := 'Override Check-in';
    v_action_type := 'override_checkin';
    v_details := format('Allowed %s(Pay Later) expired member %s (%s) to attend',
      CASE WHEN p_pay_later THEN '(Pay Later) ' ELSE '' END,
      v_member.id, v_member.name);
  ELSE
    v_action := 'Check-in';
    v_action_type := 'checkin';
    v_details := format('Normal check-in: %s (%s), session deducted (%s remaining)',
      v_member.id, v_member.name, v_new_remaining);
  END IF;

  -- Insert audit log
  INSERT INTO public.audit_logs (action, action_type, performed_by, performer_name, member_id, member_name, details)
  VALUES (v_action, v_action_type, p_performed_by, p_performer_name, p_member_id, v_member.name, v_details);

  -- Insert check-in record
  INSERT INTO public.check_ins (member_id, checked_in_by, is_override, pay_later)
  VALUES (p_member_id, p_performed_by, p_is_override, p_pay_later);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================================
-- MIGRATION: 014_remove_member_source.sql
-- =====================================================================

-- ============================================================
-- 014_remove_member_source.sql
-- Remove source column from members table
-- ============================================================

ALTER TABLE public.members DROP COLUMN IF EXISTS source;


-- =====================================================================
-- MIGRATION: 015_remove_totals.sql
-- =====================================================================

-- migration 015_remove_totals.sql

-- Add the new freeze_days_remaining column
ALTER TABLE public.members ADD COLUMN freeze_days_remaining int not null default 7;

-- Backfill data: remaining = max(0, total - used)
UPDATE public.members 
SET freeze_days_remaining = GREATEST(0, freeze_days_total - freeze_days_used);

-- Drop the old columns
ALTER TABLE public.members DROP COLUMN freeze_days_used;
ALTER TABLE public.members DROP COLUMN freeze_days_total;
ALTER TABLE public.members DROP COLUMN total_sessions;


-- =====================================================================
-- MIGRATION: 016_fix_checkin_rpc.sql
-- =====================================================================

-- migration 016_fix_checkin_rpc.sql

CREATE OR REPLACE FUNCTION public.check_in_member(
  p_member_id      uuid,
  p_is_override    boolean DEFAULT false,
  p_pay_later      boolean DEFAULT false,
  p_performed_by   uuid DEFAULT null,
  p_performer_name text DEFAULT 'System'
)
RETURNS void AS $$
DECLARE
  v_member     public.members%rowtype;
  v_class_coach uuid;
  v_new_remaining int;
  v_action     text;
  v_action_type text;
  v_details    text;
BEGIN
  -- Lock the member row
  SELECT * INTO v_member FROM public.members WHERE uuid = p_member_id FOR UPDATE;

  IF v_member IS NULL THEN
    RAISE EXCEPTION 'Member not found: %', p_member_id;
  END IF;

  -- Validation: Ensure sessions are available for non-override check-ins
  IF NOT p_is_override AND v_member.sessions_remaining <= 0 THEN
    RAISE EXCEPTION 'Member has no sessions remaining.';
  END IF;

  -- Decrement sessions (floor at 0, unlimited stays at 999)
  IF v_member.sessions_remaining = 999 THEN
    v_new_remaining := 999;
  ELSE
    v_new_remaining := GREATEST(0, v_member.sessions_remaining - 1);
  END IF;

  -- Update member
  UPDATE public.members
  SET sessions_remaining = v_new_remaining,
      status = CASE
        WHEN v_new_remaining <= 2 AND v_new_remaining != 999 THEN 'expiring_soon'
        ELSE status
      END
  WHERE uuid = p_member_id;

  -- Increment coach session count if applicable (based on assigned class)
  IF v_member.class_id IS NOT NULL THEN
    SELECT coach_id INTO v_class_coach FROM public.classes WHERE id = v_member.class_id;
    IF v_class_coach IS NOT NULL THEN
      UPDATE public.coaches
      SET sessions_this_month = sessions_this_month + 1
      WHERE id = v_class_coach;
    END IF;
  END IF;

  -- Build audit entry
  IF p_is_override THEN
    v_action := 'Override Check-in';
    v_action_type := 'override_checkin';
    v_details := format('Allowed %s(Pay Later) expired member %s (%s) to attend',
      CASE WHEN p_pay_later THEN '(Pay Later) ' ELSE '' END,
      v_member.id, v_member.name);
  ELSE
    v_action := 'Check-in';
    v_action_type := 'checkin';
    v_details := format('Normal check-in: %s (%s), session deducted (%s remaining)',
      v_member.id, v_member.name, v_new_remaining);
  END IF;

  -- Insert audit log
  INSERT INTO public.audit_logs (action, action_type, performed_by, performer_name, member_id, member_name, details)
  VALUES (v_action, v_action_type, p_performed_by, p_performer_name, p_member_id, v_member.name, v_details);

  -- Insert check-in record
  INSERT INTO public.check_ins (member_id, checked_in_by, is_override, pay_later)
  VALUES (p_member_id, p_performed_by, p_is_override, p_pay_later);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================================
-- MIGRATION: 017_fix_invoice_trigger.sql
-- =====================================================================

-- migration 017_fix_invoice_trigger.sql

CREATE OR REPLACE FUNCTION public.handle_invoice_created()
RETURNS trigger AS $$
DECLARE
  v_pkg public.packages%rowtype;
BEGIN
  -- Only update member if the invoice references a package
  IF NEW.package_id IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT * INTO v_pkg FROM public.packages WHERE id = NEW.package_id;

  IF v_pkg IS NULL THEN
    RETURN NEW;
  END IF;

  UPDATE public.members
  SET
    package_id                = v_pkg.id,
    package_name              = v_pkg.name,
    sessions_remaining        = v_pkg.sessions,
    freeze_days_remaining     = v_pkg.freeze_days,
    invitations_remaining     = v_pkg.invitations,
    inbody_sessions_remaining = v_pkg.inbody_sessions,
    expires_at                = NEW.created_at + (v_pkg.validity_days || ' days')::interval,
    status                    = 'active'
  WHERE uuid = NEW.member_id;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================================
-- MIGRATION: 018_strict_freeze.sql
-- =====================================================================

-- migration 018_strict_freeze.sql

ALTER TABLE public.members ADD COLUMN IF NOT EXISTS frozen_until timestamptz;

CREATE OR REPLACE FUNCTION public.check_in_member(
  p_member_id      uuid,
  p_is_override    boolean DEFAULT false,
  p_pay_later      boolean DEFAULT false,
  p_performed_by   uuid DEFAULT null,
  p_performer_name text DEFAULT 'System'
)
RETURNS void AS $$
DECLARE
  v_member     public.members%rowtype;
  v_class_coach uuid;
  v_new_remaining int;
  v_action     text;
  v_action_type text;
  v_details    text;
  v_unused_freeze_days int;
BEGIN
  -- Lock the member row
  SELECT * INTO v_member FROM public.members WHERE uuid = p_member_id FOR UPDATE;

  IF v_member IS NULL THEN
    RAISE EXCEPTION 'Member not found: %', p_member_id;
  END IF;

  -- Check freeze status
  IF v_member.frozen_until IS NOT NULL AND v_member.frozen_until > now() THEN
    IF NOT p_is_override THEN
      RAISE EXCEPTION 'Member is frozen until %. Please cancel freeze to check-in.', to_char(v_member.frozen_until, 'YYYY-MM-DD');
    ELSE
      -- Calculate unused freeze days (ceiling of diff in days)
      v_unused_freeze_days := CEIL(EXTRACT(EPOCH FROM (v_member.frozen_until - now())) / 86400);
      IF v_unused_freeze_days > 0 THEN
        -- Subtract from expires_at, do NOT refund freeze_days_remaining
        UPDATE public.members
        SET 
          expires_at = expires_at - (v_unused_freeze_days || ' days')::interval,
          frozen_until = null
        WHERE uuid = p_member_id;
      ELSE
        UPDATE public.members SET frozen_until = null WHERE uuid = p_member_id;
      END IF;
    END IF;
  ELSE
    -- Just clear it if it's passed
    IF v_member.frozen_until IS NOT NULL THEN
      UPDATE public.members SET frozen_until = null WHERE uuid = p_member_id;
    END IF;
  END IF;

  -- Validation: Ensure sessions are available for non-override check-ins
  IF NOT p_is_override AND v_member.sessions_remaining <= 0 THEN
    RAISE EXCEPTION 'Member has no sessions remaining.';
  END IF;

  -- Decrement sessions (floor at 0, unlimited stays at 999)
  IF v_member.sessions_remaining = 999 THEN
    v_new_remaining := 999;
  ELSE
    v_new_remaining := GREATEST(0, v_member.sessions_remaining - 1);
  END IF;

  -- Update member
  UPDATE public.members
  SET sessions_remaining = v_new_remaining,
      status = CASE
        WHEN v_new_remaining <= 2 AND v_new_remaining != 999 THEN 'expiring_soon'
        ELSE status
      END
  WHERE uuid = p_member_id;

  -- Increment coach session count if applicable (based on assigned class)
  IF v_member.class_id IS NOT NULL THEN
    SELECT coach_id INTO v_class_coach FROM public.classes WHERE id = v_member.class_id;
    IF v_class_coach IS NOT NULL THEN
      UPDATE public.coaches
      SET sessions_this_month = sessions_this_month + 1
      WHERE id = v_class_coach;
    END IF;
  END IF;

  -- Build audit entry
  IF p_is_override THEN
    v_action := 'Override Check-in';
    v_action_type := 'override_checkin';
    v_details := format('Allowed %s(Pay Later) expired or frozen member %s (%s) to attend',
      CASE WHEN p_pay_later THEN '(Pay Later) ' ELSE '' END,
      v_member.id, v_member.name);
  ELSE
    v_action := 'Check-in';
    v_action_type := 'checkin';
    v_details := format('Normal check-in: %s (%s), session deducted (%s remaining)',
      v_member.id, v_member.name, v_new_remaining);
  END IF;

  -- Insert audit log
  INSERT INTO public.audit_logs (action, action_type, performed_by, performer_name, member_id, member_name, details)
  VALUES (v_action, v_action_type, p_performed_by, p_performer_name, p_member_id, v_member.name, v_details);

  -- Insert check-in record
  INSERT INTO public.check_ins (member_id, checked_in_by, is_override, pay_later)
  VALUES (p_member_id, p_performed_by, p_is_override, p_pay_later);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================================
-- MIGRATION: 019_custom_roles.sql
-- =====================================================================

-- ============================================================
-- 019_custom_roles.sql
-- Create roles and user_roles tables to support dynamic RBAC
-- ============================================================

-- 1. Create `roles` table
CREATE TABLE IF NOT EXISTS public.roles (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  description text,
  tabs text[] not null default '{}',
  created_at timestamptz not null default now()
);

-- 2. Create `user_roles` linking table
CREATE TABLE IF NOT EXISTS public.user_roles (
  user_id uuid not null references public.profiles(id) on delete cascade,
  role_id uuid not null references public.roles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

-- 3. Insert default roles
INSERT INTO public.roles (name, description, tabs) VALUES
  ('admin', 'Admin - full access', ARRAY['/', '/checkin', '/members', '/subscriptions', '/invoices', '/discounts', '/finance', '/daily', '/reports', '/coaches', '/classes', '/sports', '/leads', '/liabilities', '/audit', '/users']),
  ('reception', 'Reception - operational tabs', ARRAY['/', '/checkin', '/members', '/invoices', '/finance', '/coaches', '/classes', '/sports', '/daily', '/liabilities']),
  ('sales', 'Sales - members & leads only', ARRAY['/', '/members', '/leads'])
ON CONFLICT (name) DO UPDATE SET tabs = EXCLUDED.tabs, description = EXCLUDED.description;

-- 4. Migrate existing profiles data into user_roles
DO $$
DECLARE
  r_admin uuid;
  r_reception uuid;
  r_sales uuid;
BEGIN
  SELECT id INTO r_admin FROM public.roles WHERE name = 'admin';
  SELECT id INTO r_reception FROM public.roles WHERE name = 'reception';
  SELECT id INTO r_sales FROM public.roles WHERE name = 'sales';

  -- Insert mappings
  INSERT INTO public.user_roles (user_id, role_id)
  SELECT p.id, r_admin
  FROM public.profiles p
  WHERE p.role = 'admin'
  ON CONFLICT DO NOTHING;

  INSERT INTO public.user_roles (user_id, role_id)
  SELECT p.id, r_reception
  FROM public.profiles p
  WHERE p.role = 'reception'
  ON CONFLICT DO NOTHING;

  INSERT INTO public.user_roles (user_id, role_id)
  SELECT p.id, r_sales
  FROM public.profiles p
  WHERE p.role = 'sales'
  ON CONFLICT DO NOTHING;
END $$;

-- 5. Drop the old check constraint on profiles.role (if it exists)
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;

-- 6. Update handle_new_user trigger to use user_roles
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  v_role_id uuid;
  v_role_name text;
BEGIN
  -- Determine initial role name (default 'reception')
  v_role_name := coalesce(new.raw_user_meta_data->>'role', 'reception');
  
  -- Insert into profiles (keep the legacy role field for now, just in case)
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    v_role_name
  );
  
  -- Find the corresponding role ID
  SELECT id INTO v_role_id FROM public.roles WHERE name = v_role_name LIMIT 1;
  
  IF v_role_id IS NOT NULL THEN
    -- Insert into user_roles
    insert into public.user_roles (user_id, role_id)
    values (new.id, v_role_id);
  END IF;

  return new;
end;
$$ language plpgsql security definer;

-- Set up RLS for roles and user_roles
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated read access to roles"
ON public.roles FOR SELECT
TO authenticated USING (true);

CREATE POLICY "Allow authenticated read access to user_roles"
ON public.user_roles FOR SELECT
TO authenticated USING (true);


-- =====================================================================
-- MIGRATION: 020_fix_custom_roles_permissions.sql
-- =====================================================================

-- ============================================================
-- 020_fix_custom_roles_permissions.sql
-- Fix 403 Forbidden errors by disabling RLS and granting permissions
-- to match the rest of the application.
-- ============================================================

-- Disable RLS to match the rest of the schema
ALTER TABLE public.roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles DISABLE ROW LEVEL SECURITY;

-- Drop the restrictive policies added in 019
DROP POLICY IF EXISTS "Allow authenticated read access to roles" ON public.roles;
DROP POLICY IF EXISTS "Allow authenticated read access to user_roles" ON public.user_roles;

-- Grant all privileges to the Supabase client roles (anon & authenticated)
GRANT ALL ON TABLE public.roles TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.user_roles TO anon, authenticated, service_role;


-- =====================================================================
-- MIGRATION: 021_drop_legacy_role_column.sql
-- =====================================================================

-- ============================================================
-- 021_drop_legacy_role_column.sql
-- Drop the legacy 'role' column from profiles now that
-- the user_roles table is fully implemented.
-- ============================================================

-- 1. Drop the column
ALTER TABLE public.profiles DROP COLUMN IF EXISTS role;

-- 2. Update the trigger to remove the reference to the role column
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  v_role_id uuid;
  v_role_name text;
BEGIN
  -- Determine initial role name (default 'reception')
  v_role_name := coalesce(new.raw_user_meta_data->>'role', 'reception');
  
  -- Insert into profiles without the role column
  insert into public.profiles (id, email, name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1))
  );
  
  -- Find the corresponding role ID
  SELECT id INTO v_role_id FROM public.roles WHERE name = v_role_name LIMIT 1;
  
  IF v_role_id IS NOT NULL THEN
    -- Insert into user_roles
    insert into public.user_roles (user_id, role_id)
    values (new.id, v_role_id);
  END IF;

  return new;
end;
$$ language plpgsql security definer;


-- =====================================================================
-- MIGRATION: 022_update_class_attendance_trigger.sql
-- =====================================================================

-- ============================================================
-- 022_update_class_attendance_trigger.sql
-- Automatically manage class attendance_count based on members.class_id
-- ============================================================

-- First, correct any existing attendance counts
UPDATE public.classes c
SET attendance_count = (
  SELECT count(*) FROM public.members m WHERE m.class_id = c.id
);

-- Function to handle attendance count changes
CREATE OR REPLACE FUNCTION public.handle_member_class_change()
RETURNS trigger AS $$
BEGIN
  -- If updating and the class_id didn't change, do nothing
  IF TG_OP = 'UPDATE' AND OLD.class_id IS NOT DISTINCT FROM NEW.class_id THEN
    RETURN NEW;
  END IF;

  -- Decrement old class
  IF (TG_OP = 'UPDATE' OR TG_OP = 'DELETE') AND OLD.class_id IS NOT NULL THEN
    UPDATE public.classes 
    SET attendance_count = attendance_count - 1 
    WHERE id = OLD.class_id;
  END IF;
  
  -- Increment new class
  IF (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') AND NEW.class_id IS NOT NULL THEN
    UPDATE public.classes 
    SET attendance_count = attendance_count + 1 
    WHERE id = NEW.class_id;
  END IF;
  
  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop existing trigger if it exists
DROP TRIGGER IF EXISTS trigger_member_class_change ON public.members;

-- Create the trigger
CREATE TRIGGER trigger_member_class_change
AFTER INSERT OR UPDATE OF class_id OR DELETE ON public.members
FOR EACH ROW EXECUTE FUNCTION public.handle_member_class_change();


-- =====================================================================
-- MIGRATION: 023_cleanup_coach_commission.sql
-- =====================================================================

1.

-- =====================================================================
-- MIGRATION: 024_coach_checkins_refactor.sql
-- =====================================================================

-- ============================================================
-- 024_coach_checkins_refactor.sql
-- Overhaul coach check-ins to support specific classes and 
-- remove the static sessions_this_month tracker.
-- ============================================================

-- 1. Add class_id to coach_check_ins
ALTER TABLE public.coach_check_ins 
ADD COLUMN class_id uuid REFERENCES public.classes(id) ON DELETE CASCADE;

-- 2. Drop the old unique constraint (1 check-in per day)
ALTER TABLE public.coach_check_ins 
DROP CONSTRAINT IF EXISTS coach_check_ins_coach_id_check_in_date_key;

-- 3. Add the new unique constraint (1 check-in per class per day)
-- We use NULLS NOT DISTINCT if possible, but standard UNIQUE is fine for now
ALTER TABLE public.coach_check_ins 
ADD CONSTRAINT coach_check_ins_coach_id_date_class_key UNIQUE (coach_id, check_in_date, class_id);

-- 4. Drop the obsolete sessions_this_month column from coaches
ALTER TABLE public.coaches 
DROP COLUMN IF EXISTS sessions_this_month;


-- =====================================================================
-- MIGRATION: 025_allow_multiple_coach_checkins.sql
-- =====================================================================

��- -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
 - -   0 2 5 _ a l l o w _ m u l t i p l e _ c o a c h _ c h e c k i n s . s q l 
 - -   A l l o w   c o a c h e s   t o   c h e c k   i n   m u l t i p l e   t i m e s   t o   t h e   s a m e   c l a s s   
 - -   o n   t h e   s a m e   d a y   i f   t h e y   h a v e   m u l t i p l e   s l o t s . 
 - -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
 
 A L T E R   T A B L E   p u b l i c . c o a c h _ c h e c k _ i n s   
 D R O P   C O N S T R A I N T   I F   E X I S T S   c o a c h _ c h e c k _ i n s _ c o a c h _ i d _ d a t e _ c l a s s _ k e y ; 
 
 

-- =====================================================================
-- MIGRATION: 026_clinic_packages.sql
-- =====================================================================

��- -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
 - -   0 2 6 _ c l i n i c _ p a c k a g e s . s q l 
 - -   A d d   i s _ c l i n i c   f l a g   t o   p a c k a g e s 
 - -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
 
 A L T E R   T A B L E   p u b l i c . p a c k a g e s   A D D   C O L U M N   i s _ c l i n i c   B O O L E A N   N O T   N U L L   D E F A U L T   f a l s e ; 
 
 

-- =====================================================================
-- MIGRATION: 027_lead_invitations.sql
-- =====================================================================

��- -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
 - -   0 2 7 _ l e a d _ i n v i t a t i o n s . s q l 
 - -   A d d   i n v i t i n g _ m e m b e r _ i d   t o   l e a d s 
 - -   = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
 
 A L T E R   T A B L E   p u b l i c . l e a d s   A D D   C O L U M N   i n v i t i n g _ m e m b e r _ i d   U U I D   R E F E R E N C E S   p u b l i c . m e m b e r s ( u u i d ) ; 
 
 

-- =====================================================================
-- MIGRATION: 028_invoice_activation.sql
-- =====================================================================

-- ============================================================
-- 028_invoice_activation.sql
-- Add activation_date and is_applied to invoices
-- ============================================================

-- ── 1. Add columns ───────────────────────────────
ALTER TABLE public.invoices
ADD COLUMN IF NOT EXISTS activation_date timestamp with time zone,
ADD COLUMN IF NOT EXISTS is_applied boolean NOT NULL DEFAULT false;

-- Backfill existing invoices
UPDATE public.invoices
SET activation_date = created_at, is_applied = true
WHERE activation_date IS NULL;

-- ── 2. Update trigger ───────────────────────────────
DROP TRIGGER IF EXISTS on_invoice_created ON public.invoices;

CREATE OR REPLACE FUNCTION public.handle_invoice_created()
RETURNS trigger AS $$
DECLARE
  v_pkg public.packages%rowtype;
BEGIN
  IF NEW.package_id IS NULL THEN
    NEW.is_applied := true;
    RETURN NEW;
  END IF;

  -- Default activation_date to created_at if not provided
  IF NEW.activation_date IS NULL THEN
    NEW.activation_date := NEW.created_at;
  END IF;

  SELECT * INTO v_pkg FROM public.packages WHERE id = NEW.package_id;
  IF v_pkg IS NULL THEN
    NEW.is_applied := true;
    RETURN NEW;
  END IF;

  -- If activation_date is in the future, don't apply yet
  IF NEW.activation_date > now() THEN
    NEW.is_applied := false;
    RETURN NEW;
  END IF;

  -- Otherwise, apply now
  UPDATE public.members
  SET
    package_id                = v_pkg.id,
    package_name              = v_pkg.name,
    sessions_remaining        = v_pkg.sessions,
    freeze_days_remaining     = v_pkg.freeze_days,
    invitations_remaining     = v_pkg.invitations,
    inbody_sessions_remaining = v_pkg.inbody_sessions,
    expires_at                = NEW.activation_date + (v_pkg.validity_days || ' days')::interval,
    status                    = 'active'
  WHERE uuid = NEW.member_id;

  NEW.is_applied := true;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_invoice_created_before
  BEFORE INSERT ON public.invoices
  FOR EACH ROW
  EXECUTE FUNCTION public.set_invoice_id();

-- Function to set expense ID to the max number + 1 if not provided
CREATE OR REPLACE FUNCTION public.set_expense_id()
RETURNS trigger AS $$
DECLARE
  v_max_id int;
BEGIN
  IF NEW.id IS NULL OR NEW.id = '' THEN
    SELECT max(NULLIF(regexp_replace(id, '\D', '', 'g'), '')::int) INTO v_max_id FROM public.expenses;
    IF v_max_id IS NULL THEN
      NEW.id := '1';
    ELSE
      NEW.id := (v_max_id + 1)::text;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS on_expense_created_before ON public.expenses;
CREATE TRIGGER on_expense_created_before
  BEFORE INSERT ON public.expenses
  FOR EACH ROW
  EXECUTE FUNCTION public.set_expense_id();

-- ── 3. Create activation RPC ───────────────────────────────
CREATE OR REPLACE FUNCTION public.activate_pending_subscriptions()
RETURNS void AS $$
DECLARE
  v_inv public.invoices%rowtype;
  v_pkg public.packages%rowtype;
BEGIN
  FOR v_inv IN 
    SELECT * FROM public.invoices 
    WHERE is_applied = false 
      AND activation_date <= now()
      AND package_id IS NOT NULL
    ORDER BY activation_date ASC
  LOOP
    SELECT * INTO v_pkg FROM public.packages WHERE id = v_inv.package_id;
    IF v_pkg IS NOT NULL THEN
      UPDATE public.members
      SET
        package_id                = v_pkg.id,
        package_name              = v_pkg.name,
        sessions_remaining        = v_pkg.sessions,
        freeze_days_remaining     = v_pkg.freeze_days,
        invitations_remaining     = v_pkg.invitations,
        inbody_sessions_remaining = v_pkg.inbody_sessions,
        expires_at                = v_inv.activation_date + (v_pkg.validity_days || ' days')::interval,
        status                    = 'active'
      WHERE uuid = v_inv.member_id;
    END IF;
    
    UPDATE public.invoices
    SET is_applied = true
    WHERE uuid = v_inv.uuid;
  END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================================
-- MIGRATION: 029_discount_groups.sql
-- =====================================================================

��A L T E R   T A B L E   d i s c o u n t s   A D D   C O L U M N   i s _ j o i n t   B O O L E A N   D E F A U L T   f a l s e ,   A D D   C O L U M N   j o i n t _ c o u n t   I N T E G E R   D E F A U L T   1 ;   D R O P   T A B L E   I F   E X I S T S   d i s c o u n t _ m e m b e r s ; 
 
 

-- =====================================================================
-- MIGRATION: 030_remove_discount_type.sql
-- =====================================================================

��A L T E R   T A B L E   d i s c o u n t s   D R O P   C O L U M N   I F   E X I S T S   t y p e ; 
 
 

-- =====================================================================
-- MIGRATION: 031_drop_discount_invoices.sql
-- =====================================================================

��D R O P   T A B L E   I F   E X I S T S   d i s c o u n t _ i n v o i c e s ; 
 
 

-- =====================================================================
-- MIGRATION: 032_negative_sessions.sql
-- =====================================================================

-- 032_negative_sessions.sql

-- Add session_debt column
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS session_debt int NOT NULL DEFAULT 0;

-- 1. check_in_member updates
CREATE OR REPLACE FUNCTION public.check_in_member(
  p_member_id      uuid,
  p_is_override    boolean DEFAULT false,
  p_pay_later      boolean DEFAULT false,
  p_performed_by   uuid DEFAULT null,
  p_performer_name text DEFAULT 'System'
)
RETURNS void AS $$
DECLARE
  v_member     public.members%rowtype;
  v_class_coach uuid;
  v_new_remaining int;
  v_action     text;
  v_action_type text;
  v_details    text;
  v_unused_freeze_days int;
  v_is_clinic  boolean;
BEGIN
  -- Lock the member row
  SELECT * INTO v_member FROM public.members WHERE uuid = p_member_id FOR UPDATE;

  IF v_member IS NULL THEN
    RAISE EXCEPTION 'Member not found: %', p_member_id;
  END IF;

  -- Check freeze status
  IF v_member.frozen_until IS NOT NULL AND v_member.frozen_until > now() THEN
    IF NOT p_is_override THEN
      RAISE EXCEPTION 'Member is frozen until %. Please cancel freeze to check-in.', to_char(v_member.frozen_until, 'YYYY-MM-DD');
    ELSE
      -- Calculate unused freeze days (ceiling of diff in days)
      v_unused_freeze_days := CEIL(EXTRACT(EPOCH FROM (v_member.frozen_until - now())) / 86400);
      IF v_unused_freeze_days > 0 THEN
        -- Subtract from expires_at, do NOT refund freeze_days_remaining
        UPDATE public.members
        SET 
          expires_at = expires_at - (v_unused_freeze_days || ' days')::interval,
          frozen_until = null
        WHERE uuid = p_member_id;
      ELSE
        UPDATE public.members SET frozen_until = null WHERE uuid = p_member_id;
      END IF;
    END IF;
  ELSE
    -- Just clear it if it's passed
    IF v_member.frozen_until IS NOT NULL THEN
      UPDATE public.members SET frozen_until = null WHERE uuid = p_member_id;
    END IF;
  END IF;

  -- Check if current package is clinic
  v_is_clinic := false;
  IF v_member.id = -1 THEN
    v_is_clinic := true;
  ELSIF v_member.package_id IS NOT NULL THEN
    SELECT is_clinic INTO v_is_clinic FROM public.packages WHERE id = v_member.package_id;
  END IF;

  IF p_is_override THEN
    IF v_is_clinic THEN
      RAISE EXCEPTION 'Cannot override check-in for clinic packages.';
    END IF;
    IF v_member.sessions_remaining <= -3 THEN
      RAISE EXCEPTION 'Member has reached the maximum allowed override debt of -3 sessions.';
    END IF;
  ELSE
    -- Normal check-in
    IF v_member.sessions_remaining <= 0 THEN
      RAISE EXCEPTION 'Member has no sessions remaining.';
    END IF;
  END IF;

  -- Decrement sessions (floor at 0 normally, -3 for override, unlimited stays at 999)
  IF v_member.sessions_remaining = 999 THEN
    v_new_remaining := 999;
  ELSIF p_is_override THEN
    v_new_remaining := GREATEST(-3, v_member.sessions_remaining - 1);
  ELSE
    v_new_remaining := GREATEST(0, v_member.sessions_remaining - 1);
  END IF;

  -- Update member
  UPDATE public.members
  SET sessions_remaining = v_new_remaining,
      status = CASE
        WHEN v_new_remaining <= 2 AND v_new_remaining != 999 AND v_new_remaining > 0 THEN 'expiring_soon'
        ELSE status
      END
  WHERE uuid = p_member_id;

  -- Increment coach session count if applicable (based on assigned class)
  IF v_member.class_id IS NOT NULL THEN
    SELECT coach_id INTO v_class_coach FROM public.classes WHERE id = v_member.class_id;
    IF v_class_coach IS NOT NULL THEN
      UPDATE public.coaches
      SET sessions_this_month = sessions_this_month + 1
      WHERE id = v_class_coach;
    END IF;
  END IF;

  -- Build audit entry
  IF p_is_override THEN
    v_action := 'Override Check-in';
    v_action_type := 'override_checkin';
    v_details := format('Allowed %s(Pay Later) expired or frozen member %s (%s) to attend. Session debt: %s',
      CASE WHEN p_pay_later THEN '(Pay Later) ' ELSE '' END,
      v_member.id, v_member.name, v_new_remaining);
  ELSE
    v_action := 'Check-in';
    v_action_type := 'checkin';
    v_details := format('Normal check-in: %s (%s), session deducted (%s remaining)',
      v_member.id, v_member.name, v_new_remaining);
  END IF;

  -- Insert audit log
  INSERT INTO public.audit_logs (action, action_type, performed_by, performer_name, member_id, member_name, details)
  VALUES (v_action, v_action_type, p_performed_by, p_performer_name, p_member_id, v_member.name, v_details);

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 2. handle_invoice_created update
CREATE OR REPLACE FUNCTION public.handle_invoice_created()
RETURNS trigger AS $$
DECLARE
  v_pkg public.packages%rowtype;
  v_member public.members%rowtype;
  v_new_sessions int;
  v_new_debt int;
BEGIN
  IF NEW.package_id IS NULL THEN
    NEW.is_applied := true;
    RETURN NEW;
  END IF;

  -- Default activation_date to created_at if not provided
  IF NEW.activation_date IS NULL THEN
    NEW.activation_date := NEW.created_at;
  END IF;

  SELECT * INTO v_pkg FROM public.packages WHERE id = NEW.package_id;
  IF v_pkg IS NULL THEN
    NEW.is_applied := true;
    RETURN NEW;
  END IF;

  -- If activation_date is in the future, don't apply yet
  IF NEW.activation_date > now() THEN
    NEW.is_applied := false;
    RETURN NEW;
  END IF;

  -- Fetch the member to check for session debt
  SELECT * INTO v_member FROM public.members WHERE uuid = NEW.member_id;
  IF v_member IS NULL THEN
    NEW.is_applied := true;
    RETURN NEW;
  END IF;

  -- Calculate new sessions with debt
  IF v_pkg.is_clinic THEN
    v_new_sessions := v_pkg.sessions;
    v_new_debt := v_member.session_debt;
    IF v_member.sessions_remaining < 0 THEN
      v_new_debt := v_new_debt + ABS(v_member.sessions_remaining);
    END IF;
  ELSE
    v_new_debt := v_member.session_debt;
    IF v_member.sessions_remaining < 0 THEN
      v_new_debt := v_new_debt + ABS(v_member.sessions_remaining);
    END IF;
    
    v_new_sessions := v_pkg.sessions - v_new_debt;
    v_new_debt := 0;
  END IF;

  -- Otherwise, apply now
  UPDATE public.members
  SET
    package_id                = v_pkg.id,
    package_name              = v_pkg.name,
    sessions_remaining        = v_new_sessions,
    session_debt              = v_new_debt,
    freeze_days_remaining     = v_pkg.freeze_days,
    invitations_remaining     = v_pkg.invitations,
    inbody_sessions_remaining = v_pkg.inbody_sessions,
    expires_at                = NEW.activation_date + (v_pkg.validity_days || ' days')::interval,
    status                    = 'active'
  WHERE uuid = NEW.member_id;

  NEW.is_applied := true;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 3. activate_pending_subscriptions update
CREATE OR REPLACE FUNCTION public.activate_pending_subscriptions()
RETURNS void AS $$
DECLARE
  v_inv public.invoices%rowtype;
  v_pkg public.packages%rowtype;
  v_member public.members%rowtype;
  v_new_sessions int;
  v_new_debt int;
BEGIN
  FOR v_inv IN 
    SELECT * FROM public.invoices 
    WHERE is_applied = false 
      AND activation_date <= now()
      AND package_id IS NOT NULL
    ORDER BY activation_date ASC
  LOOP
    SELECT * INTO v_pkg FROM public.packages WHERE id = v_inv.package_id;
    IF v_pkg IS NOT NULL THEN
      
      SELECT * INTO v_member FROM public.members WHERE uuid = v_inv.member_id;
      
      IF v_member IS NOT NULL THEN
        IF v_pkg.is_clinic THEN
          v_new_sessions := v_pkg.sessions;
          v_new_debt := v_member.session_debt;
          IF v_member.sessions_remaining < 0 THEN
            v_new_debt := v_new_debt + ABS(v_member.sessions_remaining);
          END IF;
        ELSE
          v_new_debt := v_member.session_debt;
          IF v_member.sessions_remaining < 0 THEN
            v_new_debt := v_new_debt + ABS(v_member.sessions_remaining);
          END IF;
          
          v_new_sessions := v_pkg.sessions - v_new_debt;
          v_new_debt := 0;
        END IF;

        UPDATE public.members
        SET
          package_id                = v_pkg.id,
          package_name              = v_pkg.name,
          sessions_remaining        = v_new_sessions,
          session_debt              = v_new_debt,
          freeze_days_remaining     = v_pkg.freeze_days,
          invitations_remaining     = v_pkg.invitations,
          inbody_sessions_remaining = v_pkg.inbody_sessions,
          expires_at                = v_inv.activation_date + (v_pkg.validity_days || ' days')::interval,
          status                    = 'active'
        WHERE uuid = v_inv.member_id;
      END IF;
    END IF;
    
    UPDATE public.invoices
    SET is_applied = true
    WHERE uuid = v_inv.uuid;
  END LOOP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =====================================================================
-- MIGRATION: 033_auto_admin.sql
-- =====================================================================

-- ============================================================
-- 033_auto_admin.sql
-- Automatically make the first registered user an Admin
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  v_role_id uuid;
  v_role_name text;
  v_user_count int;
BEGIN
  -- Check if this is the very first user in the database
  SELECT count(*) INTO v_user_count FROM public.profiles;

  IF v_user_count = 0 THEN
    v_role_name := 'admin';
  ELSE
    -- Determine initial role name (default 'reception')
    v_role_name := coalesce(new.raw_user_meta_data->>'role', 'reception');
  END IF;
  
  -- Insert into profiles (keep the legacy role field for now)
  insert into public.profiles (id, email, name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    v_role_name
  );
  
  -- Find the corresponding role ID
  SELECT id INTO v_role_id FROM public.roles WHERE name = v_role_name LIMIT 1;
  
  IF v_role_id IS NOT NULL THEN
    -- Insert into user_roles
    insert into public.user_roles (user_id, role_id)
    values (new.id, v_role_id);
  END IF;

  return new;
end;
$$ language plpgsql security definer;


-- =====================================================================
-- MIGRATION: 034_numeric_invoice_ids.sql
-- =====================================================================

-- Remove the old sequence default
ALTER TABLE public.invoices ALTER COLUMN id DROP DEFAULT;

CREATE SEQUENCE IF NOT EXISTS public.expense_display_id_seq START 1;

-- Function to set invoice ID to the max number + 1 if not provided
CREATE OR REPLACE FUNCTION public.set_invoice_id()
RETURNS trigger AS $$
DECLARE
  v_max_id int;
BEGIN
  IF NEW.id IS NULL OR NEW.id = '' THEN
    SELECT max(NULLIF(regexp_replace(id, '\D', '', 'g'), '')::int) INTO v_max_id FROM public.invoices;
    IF v_max_id IS NULL THEN
      v_max_id := 1000;
    END IF;
    NEW.id := (v_max_id + 1)::text;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_invoice_id ON public.invoices;
CREATE TRIGGER trg_set_invoice_id
  BEFORE INSERT ON public.invoices
  FOR EACH ROW
  EXECUTE FUNCTION public.set_invoice_id();

-- Update existing records to remove the 'INV-' prefix
UPDATE public.invoices SET id = replace(id, 'INV-', '') WHERE id LIKE 'INV-%';


-- ── Trigger: auto-rollback member subscription on invoice deletion ──

CREATE OR REPLACE FUNCTION public.handle_invoice_deleted()
RETURNS trigger AS $$
DECLARE
  v_pkg public.packages%rowtype;
  v_member public.members%rowtype;
  v_latest_inv public.invoices%rowtype;
BEGIN
  -- 1. Only process if the invoice was actually applied
  IF OLD.is_applied = false THEN
    RETURN OLD;
  END IF;

  -- 2. Only process if the invoice had a package
  IF OLD.package_id IS NULL THEN
    RETURN OLD;
  END IF;

  SELECT * INTO v_pkg FROM public.packages WHERE id = OLD.package_id;
  IF v_pkg IS NULL THEN
    RETURN OLD;
  END IF;

  SELECT * INTO v_member FROM public.members WHERE uuid = OLD.member_id;
  IF v_member IS NULL THEN
    RETURN OLD;
  END IF;

  -- 3. Determine if this invoice is the member's current/latest active subscription
  SELECT * INTO v_latest_inv
  FROM public.invoices
  WHERE member_id = OLD.member_id
    AND is_applied = true
    AND package_id IS NOT NULL
  ORDER BY activation_date DESC NULLS LAST, created_at DESC
  LIMIT 1;

  -- 4. If the invoice being deleted IS the latest applied invoice, roll back the balances
  IF v_latest_inv.uuid = OLD.uuid THEN
    UPDATE public.members
    SET
      sessions_remaining        = GREATEST(0, v_member.sessions_remaining - v_pkg.sessions),
      freeze_days_remaining     = GREATEST(0, v_member.freeze_days_remaining - v_pkg.freeze_days),
      invitations_remaining     = GREATEST(0, v_member.invitations_remaining - v_pkg.invitations),
      inbody_sessions_remaining = GREATEST(0, v_member.inbody_sessions_remaining - v_pkg.inbody_sessions),
      package_id                = NULL,
      package_name              = 'None',
      status                    = 'expired'
    WHERE uuid = OLD.member_id;
  END IF;

  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_invoice_deleted_before ON public.invoices;
CREATE TRIGGER on_invoice_deleted_before
  BEFORE DELETE ON public.invoices
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_invoice_deleted();

-- Function to set member ID to the max number + 1 if it is 0 or null
CREATE OR REPLACE FUNCTION public.set_member_id()
RETURNS trigger AS $$
DECLARE
  v_max_id int;
BEGIN
  IF NEW.id IS NULL OR NEW.id = 0 THEN
    SELECT max(id) INTO v_max_id FROM public.members WHERE id > 0;
    IF v_max_id IS NULL THEN
      v_max_id := 0;
    END IF;
    NEW.id := v_max_id + 1;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_member_id ON public.members;
CREATE TRIGGER trg_set_member_id
  BEFORE INSERT ON public.members
  FOR EACH ROW
  EXECUTE FUNCTION public.set_member_id();

